### ISSUE TITLE
【错误】在运行demo里的demo_qwen_agent.ipynb时出现问题 

### ISSUE THREAD

**Issue by Astrallee** [modelscope/modelscope-agent#108]
部署在本地的jupyter。
完全是跟着demo走的。
在运行到run阶段得到如下错误

![image](https://github.com/modelscope/modelscope-agent/assets/48097779/63089b99-325e-4f59-802b-5c35e73777ca)

**Comment by thor9king** [comment]
一个bug, 在modelscope notebook里同样报这个错。
直接把 modelscope_agent/prompt/raw_prompt_builder.py 里的函数改掉，可以跑通DEMO
def build_raw_prompt(model_name):
    return plate_preprocessor

因model_name不是str，而是个模型类

**Comment by zzclynn** [comment]
感谢提醒，我们马上检查一遍demo并修正，最近有更新，没有及时同步。

**Comment by Astrallee** [comment]
> 一个bug, 在modelscope notebook里同样报这个错。 直接把 modelscope_agent/prompt/raw_prompt_builder.py 里的函数改掉，可以跑通DEMO def build_raw_prompt(model_name): return plate_preprocessor
> 
> 因model_name不是str，而是个模型类

这个办法我尝试了一下，依旧没有解决我的问题，可能是楼下讲的更新没有同步的问题。 按照你的提议改之后的报错如下图：

![image](https://github.com/modelscope/modelscope-agent/assets/48097779/59cde0e2-3230-4184-be4b-63d933313c0b)

**Comment by Astrallee** [comment]
> 感谢提醒，我们马上检查一遍demo并修正，最近有更新，没有及时同步。

等待您这边回复~

**Comment by zzclynn** [comment]
这边做了调整，在review中，你可以先在分支上跑起来
