### ISSUE TITLE
baichuan13b运行出错：BaichuanForCausalLM.chat() got an unexpected keyword argument 'history'

### ISSUE THREAD

**Issue by Yu-Yang-Li** [modelscope/modelscope-agent#16]
修改为baichuan13b参数
运行demo_qwen_agent.ipynb：

agent.reset()

agent.run('使用地址识别模型，从下面的地址中找到省市区等元素，地址：浙江杭州市江干区九堡镇三村村一区', remote=False)

报错：
BaichuanForCausalLM.chat() got an unexpected keyword argument 'history'

**Comment by Yu-Yang-Li** [comment]
对于chatglm2-6b:

from modelscope_agent.llm import LLMFactory
from modelscope.hub.api import HubApi

model_name = 'ZhipuAI/chatglm2-6b'
model_cfg = {
    'ZhipuAI/chatglm2-6b':{
        'model_id': 'ZhipuAI/chatglm2-6b',
        'model_revision': 'v1.0.9'
    }
}


llm = LLMFactory.build_llm(model_name, model_cfg)

报错：
ValueError: Unrecognized configuration class  for this kind of AutoModel: AutoModelForCausalLM.

请问原因是未支持吗？

**Comment by amwork2020** [comment]
DEFAULT_CHATGPT_PROMPT_TEMPLATE 没定义？

**Comment by Zhikaiiii** [comment]
我这边试了一下，baichuan-13b可以使用如下的config
```
model_name = 'Baichuan-13B-Chat'
model_cfg = {
    'Baichuan-13B-Chat':{
        'model_id': 'baichuan-inc/Baichuan-13B-Chat',
        'model_revision': 'v1.0.3',
        'use_raw_generation_config': False,
        'custom_chat': False,
        'generate_cfg':{
            'do_sample': True,
            'max_new_tokens': 512,
            'top_k': 10
        }
    }
}
```
chatglm2-6b可以用如下的config起
```
model_name = 'chatglm2-6b'
model_cfg = {
    'chatglm2-6b':{
        'model_id': 'ZhipuAI/chatglm2-6b',
        'model_revision': 'v1.0.7',
        'use_raw_generation_config': False,
        'custom_chat': False,
        'model_cls': AutoModel,
        'generate_cfg':{
            'do_sample': True,
            'max_new_tokens': 512,
            'top_k': 10
        }
    }
}
```
