### ISSUE TITLE
 请问evaluate脚本和数据有开源么？

### ISSUE THREAD

**Issue by Mervyn-1** [modelscope/modelscope-agent#171]
rt

**Comment by zzclynn** [comment]
这里目前主要是agent应用，你说的evaluate脚本是指？

**Comment by Mervyn-1** [comment]
就是得到论文附录B.2中Evaluation结果的评测脚本，docs/training_llms/train.md中的evaluate中的内容，看起来还没补全？

**Comment by lcl6679292** [comment]
> 就是得到论文附录B.2中Evaluation结果的评测脚本，docs/training_llms/train.md中的evaluate中的内容，看起来还没补全？

inference的脚本已经开出去了，可以看下面这个代码文件，文档这块我们补全一下

https://github.com/modelscope/modelscope-agent/blob/master/demo/tool_agent_finetune_swift/llm_infer.py

**Comment by Mervyn-1** [comment]
使用这个infer脚本，模型是ModelScope-Agent-7B，infer的内容质量很低，输出大量空白，请问这个是因为什么呢？
