### ISSUE TITLE
是否有跑在服务端的demo

### ISSUE THREAD

**Issue by lucasjinreal** [modelscope/modelscope-agent#174]
对于agents，目前大多是跑在客户端，例如 python 调用，然后内部调用大模型的server，根据返回结果来取相应的值。

是否可以想openai一样包装一个 server端的实现，客户端不需要关心agents具体如何实现，然后通过OpenAI的schema来与客户端协调，例如在ChatMessages 里面通过function, tool 等参数进行交互。

**Comment by wenmengzhou** [comment]
你是想要类似openai的assistant api？

**Comment by lucasjinreal** [comment]
封装在服务端的agent实现

**Comment by zzclynn** [comment]
暂时还没有，目前还是面向开发者去做一些实验。后续考虑。
