### ISSUE TITLE
使用Qwen-7B时，模型的回复无法准确结束

### ISSUE THREAD

**Issue by KevinWang676** [modelscope/modelscope-agent#177]
请问有朋友遇到这种问题吗，Qwen-7B回复之后继续输出应该截止的内容。想知道是什么的问题

![image](https://github.com/modelscope/modelscope-agent/assets/126712357/35684d8c-6996-43bf-bb3b-3a933398d6aa)

**Comment by KevinWang676** [comment]
![image](https://github.com/modelscope/modelscope-agent/assets/126712357/e02ffef1-f1fb-4199-b977-117ee124dc90)

使用 Qwen-14B 也会出现同样的情况

**Comment by slin000111** [comment]
你好，本地部署的中枢大模型吗？

**Comment by KevinWang676** [comment]
@slin000111 是的，你有发现同样的问题吗

**Comment by zzclynn** [comment]
7b的指令理解还不够，建议使用更大规模的模型。

**Comment by enelguo** [comment]
stop token制定一下，好像是</s>?

**Comment by KevinWang676** [comment]
@enelguo 有找到 `stop token` 是在哪里设置的吗？谢谢！
