### ISSUE TITLE
请问可以提供demo的界面代码吗？

### ISSUE THREAD

**Issue by jayden222** [modelscope/modelscope-agent#19]
这个[demo](https://modelscope.cn/studios/damo/ModelScopeGPT/summary/)的演示代码可以开源吗？

**Comment by yingdachen** [comment]
https://www.modelscope.cn/studios/damo/ModelScopeGPT/file/view/master/app.py

**Comment by jayden222** [comment]
这个空间文件有统一下载的方法吗？

**Comment by wenmengzhou** [comment]
参考文档 https://modelscope.cn/docs/%E5%88%9B%E7%A9%BA%E9%97%B4%E5%88%9B%E5%BB%BA%E4%B8%8E%E6%90%AD%E5%BB%BA

```shell
git lfs install
  #根据实际情况填写
git clone http://oauth2:<your_access_token>@www.modelscope.cn/studios/<your_studio_path>/<your_studio_name>.git
```

**Comment by jayden222** [comment]
好了，感谢~

**Comment by wenmengzhou** [comment]
可以参考下notebook中示例，所有模块均可本地运行
https://github.com/modelscope/modelscope-agent/blob/master/demo/demo_qwen_agent.ipynb

**Comment by amwork2020** [comment]
> 可以参考下notebook中示例，所有模块均可本地运行 https://github.com/modelscope/modelscope-agent/blob/master/demo/demo_qwen_agent.ipynb

你模型训练的json文件是什么
![image](https://github.com/modelscope/modelscope-agent/assets/67415734/45414344-7db8-4120-9208-5c2cd479e0d3)

**Comment by lcl6679292** [comment]
> > 可以参考下notebook中示例，所有模块均可本地运行 https://github.com/modelscope/modelscope-agent/blob/master/demo/demo_qwen_agent.ipynb
> 
> 你模型训练的json文件是什么 ![image](https://user-images.githubusercontent.com/67415734/266518631-45414344-7db8-4120-9208-5c2cd479e0d3.png)

这个训练数据我们也有提供的，可以下面链接获取

https://modelscope.cn/datasets/damo/MSAgent-Bench/summary
