### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wangyijunlyy** [modelscope/modelscope-agent#192]
![image](https://github.com/modelscope/modelscope-agent/assets/110682983/b0cb8384-535e-48fb-b639-ec0420570f15)
当本地重新运行app.py，直接刷新上次打开的http://127.0.0.1:7860/  页面，init会卡死，必须重新打开一个web页面，以前是可以直接刷新的

**Comment by wangyijunlyy** [comment]
空间会卡死，发送按钮一直在加载中，init不成功
![image](https://github.com/modelscope/modelscope-agent/assets/110682983/af821382-d56a-46ab-ab22-401b8dd73e92)

**Comment by zzclynn** [comment]
现在还有么？

**Comment by cxj01** [comment]
还会有

**Comment by zzhangpurdue** [comment]
目前新版本已经修复相关功能，请使用最新master运行

**Comment by zzhangpurdue** [comment]
长时间未响应，有问题重新开。
