### ISSUE TITLE
报错'ToolSchema' object has no attribute 'model_dump_json'

### ISSUE THREAD

**Issue by AIGoBig** [modelscope/modelscope-agent#193]
运行demo的ipynb会报错 'ToolSchema' object has no attribute 'model_dump_json'

**Comment by slin000111** [comment]
你贴一下demo链接

**Comment by zzclynn** [comment]
升级到pydantic 2.0+版本

**Comment by AIGoBig** [comment]
升级后transformer会报错

**Comment by UrsulaPan** [comment]
> 升级到pydantic 2.0+版本

![微信截图_20240204221754](https://github.com/modelscope/modelscope-agent/assets/22795031/02178cbd-c27c-4a62-84a0-98353431f31b)
pydantic 2.6.0也出现一样的问题
