### ISSUE TITLE
demo_chatgpt.ipynb运行报错

### ISSUE THREAD

**Issue by gorwayne** [modelscope/modelscope-agent#20]
cannot import name 'DEFAULT_CHATGPT_PROMPT_TEMPLATE' from 'modelscope_agent.prompt'

**Comment by lcl6679292** [comment]
您好，这个问题我们已经关注到了，正在修复，修复完成后会第一时间通知您

**Comment by lcl6679292** [comment]
您好，这个已经修复好了，请拉取最新的代码，使用demo_chatgpt.ipynb
