### ISSUE TITLE
工具不能正确调用

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [modelscope/modelscope-agent#210]
Modelscope AgentFabric的勾选了所有工具，但都不能主动调用，需要显示的说明，可能的原因是什么呢？用了qwen的各种模型都不行。

**Comment by zzclynn** [comment]
可以在builder侧多试试各种prompt，激发模型能力

**Comment by shanmu-raoyunfei** [comment]
问题已解决，没有正确配置tools的key
