### ISSUE TITLE
多次调用自定义tool

### ISSUE THREAD

**Issue by kapiya** [modelscope/modelscope-agent#224]
我参照demo写了一个自定义tool，每次run后，多出现多次round，最周输出结果也是多条重复数据
![image](https://github.com/modelscope/modelscope-agent/assets/27723450/c3cfa200-2c25-4643-84b1-c0fa455d45b1)

这个round的机制是怎样的，可以控制吗？

**Comment by zzclynn** [comment]
round的机制是完全靠llm以及对应的prompt控制，目前最新版本主要是roleplay 这个agent在控制，可以看最新的代码看一下。

**Comment by zzhangpurdue** [comment]
长时间未响应，有问题重新开。
