### ISSUE TITLE
本地运行app.py异常：ModuleNotFoundError: No module named 'modelscope_agent'

### ISSUE THREAD

**Issue by haiwang2517** [modelscope/modelscope-agent#226]
mac 启动异常
```
(venv) ken@V_FENGWFENG-MB2 agentfabric % python app.py                   
Traceback (most recent call last):
  File "/Users/ken/software/ai/modelscope-agent/apps/agentfabric/app.py", line 10, in <module>
    from builder_core import beauty_output, init_builder_chatbot_agent
  File "/Users/ken/software/ai/modelscope-agent/apps/agentfabric/builder_core.py", line 6, in <module>
    from builder_prompt import BuilderPromptGenerator
  File "/Users/ken/software/ai/modelscope-agent/apps/agentfabric/builder_prompt.py", line 1, in <module>
    from modelscope_agent.prompt import MessagesGenerator
ModuleNotFoundError: No module named 'modelscope_agent'
```

执行步骤,参考[Agent实操（五）：如何在本地/云端创建并发布更定制化的Agent](https://developer.aliyun.com/article/1393877?spm=a2c6h.17735062.detail.34.69e01406IdUsEB)：
```shell
git clone https://github.com/modelscope/modelscope-agent
cd apps/agentfabric
pip install modelscope
pip install ".[nlp]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
pip install -r requirements.txt
python app.py
```

**Comment by slin000111** [comment]
在clone下来的你的创空间LocalAgent目录下，运行python app.py。

**Comment by bariselci** [comment]
(venv) D:\AIs\ModelScope Agent>python app.py
Traceback (most recent call last):
  File "D:\AIs\ModelScope Agent\app.py", line 11, in <module>
    from builder_core import beauty_output, init_builder_chatbot_agent
  File "D:\AIs\ModelScope Agent\builder_core.py", line 6, in <module>
    from builder_prompt import BuilderPromptGenerator
  File "D:\AIs\ModelScope Agent\builder_prompt.py", line 1, in <module>
    from modelscope_agent.prompt import MessagesGenerator
ModuleNotFoundError: No module named 'modelscope_agent'

pip install modelscope / didn't work
pip install modelscope_agent / no such repository
https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html this repo does download as an html file, doesn't view. Inside the repo.html file there is a [modelscope_agent-0.2.5rc0-py3-none-any.whl](https://modelscope.oss-cn-beijing.aliyuncs.com/releases/v0.2/modelscope_agent-0.2.5rc0-py3-none-any.whl)
is not allowed to access to

**Comment by zzclynn** [comment]
please download the repo, and add the modelscope_agent folder to pythonpath

**Comment by zzhangpurdue** [comment]
长时间未响应，有问题重新开。

**Comment by xiaoxiaoshiyuan** [comment]
'error': 'llm result is not valid. parse RichConfig error'运行app.py时，出现错误
