### ISSUE TITLE
建议：精简/优化第三方库的导入，避免引入过多无用依赖

### ISSUE THREAD

**Issue by Tangent-90C** [modelscope/modelscope-agent#234]
最近在一个ECS示例上用modelscope-agent部署Agent，体验极差。

我并不需要任何的本地推理服务，所有推理服务都是调用dashscope完成的，顶多涉及到一些网络IO请求，但modelscope-agent硬生生捆绑了近7G的无用环境，包括torch、transformers、modelscope等推理库，这些库明明用不到，一删就不能用了，甚至连微调模型用的ms-swift都给我塞进去了，然而代码里并没有一处地方有用到这框架。

最终，我用docker打包个安装有modelscope-agent的环境，占用了我7.25G的存储空间。
![ebb632e99428d9e09f6b4f540396d36](https://github.com/modelscope/modelscope-agent/assets/28804414/867e6502-c103-4e44-b232-10af810b3ee1)

建议modelscope-agent可以像langchain一样，各种包只有被调用到时才import。
或者提供个lite版本，砍掉对ECS几乎无用的本地推理功能。

**Comment by zzclynn** [comment]
嗯，我们正在做这样的调整，感谢建议

**Comment by zzclynn** [comment]
新版本，目前去掉了较大的torch和nvidia库依赖，只有使用特定本地模型的时候会提示安装。
