### ISSUE TITLE
调用远程文字转图片报错

### ISSUE THREAD

**Issue by beixiang-l** [modelscope/modelscope-agent#236]
本地环境：
unbuntu 20.04
P40 GPU
CUDA11.3 

# Multi-turn tool-use
agent.reset()
agent.run('写一个20字左右简短的小故事')
agent.run('给这个故事配一张图',remote=True)

**************************************************round 1**************************************************
有个孩子在海边捡到了一只受伤的海鸟，他带着海鸟回家，照顾它直到它恢复健康，然后放飞了它。
**************************************************round 1**************************************************

ValueError                                Traceback (most recent call last)
Cell In[7], line 4
      2 agent.reset()
      3 agent.run('写一个20字左右简短的小故事')
----> 4 agent.run('给这个故事配一张图',remote=True)

File /home/modelscope-agent/modelscope_agent/agent.py:248, in AgentExecutor.run(self, task, remote, print_info, append_files, **kwargs)
    245     return [{'exec_result': exec_result}]
    247 # display result
--> 248 display(llm_result, exec_result, idx, self.agent_type)

File /home/modelscope-agent/modelscope_agent/output_wrapper.py:209, in display(llm_result, exec_result, idx, agent_type)
    205 exec_result = exec_result.get('result', '')
    207 if isinstance(exec_result, ImageWrapper) or isinstance(
    208         exec_result, VideoWrapper):
--> 209     display(Image(exec_result.path))
    210 elif isinstance(exec_result, AudioWrapper):
    211     display(Audio(exec_result.path))

File /opt/conda/envs/agent/lib/python3.8/site-packages/IPython/core/display.py:966, in Image.__init__(self, data, url, filename, format, embed, width, height, retina, unconfined, metadata, alt)
    963 self.embed = embed if embed is not None else (url is None)
    965 if self.embed and self.format not in self._ACCEPTABLE_EMBEDDINGS:
--> 966     raise ValueError("Cannot embed the '%s' image format" % (self.format))
    967 if self.embed:
    968     self._mimetype = self._MIMETYPES.get(self.format)

ValueError: Cannot embed the 'png?expires=1703556890&ossaccesskeyid=ltai5tqzd8aeczx6kzv4g8ql&signature=o%2bx2iiqhnr7hrl%2bz2vdnx%2bph0cu%3d' image format

**Comment by slin000111** [comment]
可参考https://github.com/modelscope/modelscope-agent/blob/master/demo/demo_qwen_agent.ipynb中建议：部署在本地，将remote=False。

**Comment by zzhangpurdue** [comment]
长时间未响应，有问题重新开。
