### ISSUE TITLE
demo里面的用例有些过时了，更新下用例吧

### ISSUE THREAD

**Issue by JUN-ZZ** [modelscope/modelscope-agent#238]
from modelscope_agent.output_parser import MsOutputParser, MRKLOutputParser
from modelscope_agent.action_parser import MsActionParser
output_parser 已经看不到了 ，估计是换成这个模块了action_parser

**Comment by zzclynn** [comment]
我们尽快更新。

**Comment by zzclynn** [comment]
已经完成更新
