### ISSUE TITLE
仓库中没有utils啊

### ISSUE THREAD

**Issue by chenggb123** [modelscope/modelscope-agent#24]

**Comment by lcl6679292** [comment]
可以提供详细的报错信息吗，是在运行哪个部分代码时候仓库没有utils

**Comment by chenggb123** [comment]
from modelscope.utils.config import  提示找不到utils

**Comment by Zhikaiiii** [comment]
> from modelscope.utils.config import 提示找不到utils

可以麻烦截图看一下你的modelscope版本吗？这个似乎是modelscope的版本问题。
