### ISSUE TITLE
modescope agent 训练Qwen 为什么采用<|user|>而不是<|im_start|>

### ISSUE THREAD

**Issue by Scarlett-H** [modelscope/modelscope-agent#241]
modescope agent 训练Qwen 代码里的数据格式为什么采用<|user|>而不是像Qwen代码里用的<|im_start|>，只要是特殊字符就可以吗，会不会和Chat的训练格式不一致，导致效果有问题呢

**Comment by 5663015** [comment]
我也有这个问题，我觉得如果是agent数据和对话数据一起训练的话还是统一比较好。
我看代码，agent训练用的是qwen的base模型，数据格式就可以随便自定义了。如果是用chat模型，还是得和chat模型的格式一致才行。

**Comment by zzhangpurdue** [comment]
modescope agent 后续版本的模型会对齐qwen的格式。
