### ISSUE TITLE
模型下载出错

### ISSUE THREAD

**Issue by timegoby** [modelscope/modelscope-agent#245]
![1704271835671](https://github.com/modelscope/modelscope-agent/assets/48506074/f9454964-1a3f-4c04-9fae-c91d9e8b9233)

LLM模型下载出错，有手动下载方式吗？

**Comment by slin000111** [comment]
snapshot_download或git下载，https://modelscope.cn/docs/%E6%A8%A1%E5%9E%8B%E7%9A%84%E4%B8%8B%E8%BD%BD

**Comment by timegoby** [comment]
我找到模型是自动下载到 ~/.cache/modelscope/hub 这个目录下，现在我手动把下载好的14.4G模型文件上传到该目录下，为什么还是会触发重新下载呢？
![1704440694027](https://github.com/modelscope/modelscope-agent/assets/48506074/a575e010-8ffa-4292-83d1-d5f8e84b26fb)

**Comment by slin000111** [comment]
Q5, https://modelscope.cn/docs/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
