### ISSUE TITLE
运行demo_modelscopegpt_agent时出错

### ISSUE THREAD

**Issue by yuxwang123** [modelscope/modelscope-agent#25]
当我运行demo_modelscopegpt_agent代码运行到以下步骤时出现错误，请问一下如何解决？
![Screenshot from 2023-09-09 17-49-38](https://github.com/modelscope/modelscope-agent/assets/95109550/226163b9-bd57-4d26-8c26-33606f29d72d)

**Comment by gorwayne** [comment]
照着demo里面更新一下新的配置文件。新的配置文件字段和老的不一样了。
