### ISSUE TITLE
openapi schema解析不完全

### ISSUE THREAD

**Issue by zhengxiang5965** [modelscope/modelscope-agent#259]
{
  "openapi": "3.0.3",
  "info": {
    "title": "Open copilot api - OpenAPI 3.0",
    "description": "open copilot 使用API列表",
    "contact": {
      "email": "zheng.xiang@vnet.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.11"
  },
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "http://swagger.io"
  },
  "servers": [
    {
      "url": "https://api.vvhan.com/api"
    }
  ],
  "tags": [
    {
      "name": "util",
      "description": "Everything about your util"
    }
  ],
  "paths": {
    "/getIpInfo": {
      "get": {
        "tags": [
          "util"
        ],
        "description": "Query the attribution of the specified IP",
        "operationId": "findIPLocation",
        "parameters": [
          {
            "name": "ip",
            "in": "query",
            "description": "IP address to be enquired",
            "required": true,
            "explode": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/IpResp"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid status value"
          }
        }
      }
    },
    "/title": {
      "get": {
        "tags": [
          "util"
        ],
        "description": "Query the site title of a specified URL",
        "operationId": "queryWebsiteTitle",
        "parameters": [
          {
            "name": "url",
            "in": "query",
            "description": "website url",
            "required": true,
            "explode": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/TitleResp"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid tag value"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "IpResp": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "ip": {
            "type": "string",
            "example": "192.168.233.48"
          },
          "info": {
            "type": "object",
            "properties": {
              "country": {
                "type": "string",
                "example": "中国"
              },
              "prov": {
                "type": "string",
                "example": "香港",
                "description": "province"
              },
              "city": {
                "type": "string",
                "example": "-"
              },
              "lsp": {
                "type": "string",
                "description": "Layered Service Provider",
                "example": "阿里云"
              }
            }
          }
        }
      },
      "TitleResp": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "title": {
            "type": "string",
            "example": "百度一下，你就知道"
          }
        }
      }
    }
  }
}

GET请求参数在query段的这种，工具发起请求都在requestbody里以json格式传递

**Comment by zzclynn** [comment]
我们测试一下。

**Comment by zzhangpurdue** [comment]
#294 fixed this, please double check the latest master

**Comment by zzhangpurdue** [comment]
长时间未响应，有问题重新开。
