### ISSUE TITLE
预训练代码报错

### ISSUE THREAD

**Issue by timegoby** [modelscope/modelscope-agent#265]
qwen/Qwen-7B预训练模型已经把pytoch_model.bin分开成了多份，但是代码里验证和加载方式还是之前的？
![1705048027678](https://github.com/modelscope/modelscope-agent/assets/48506074/029a2ffb-f9b8-40ae-9a7f-a01d463a271f)

**Comment by mushenL** [comment]
我们检查一下，后面会整体调整更新

**Comment by timegoby** [comment]
好的

**Comment by timegoby** [comment]
好的，谢谢
这样的话，我修改报错的代码，用最新版本的qwen/Qwen-7B也可以进行预训练吧

**Comment by mushenL** [comment]
您好，这个问题已经在最新版本中修复
