### ISSUE TITLE
这个训练微调对自定义功能API tool的调用识别极低

### ISSUE THREAD

**Issue by zhengxiang5965** [modelscope/modelscope-agent#27]
![image](https://github.com/modelscope/modelscope-agent/assets/31379313/d9a2335f-a01d-4d77-b9b8-e41c635e1fff)

**Comment by zhengxiang5965** [comment]
特别是稳定性 比如我图片这个问题，问题不变，10次调用，结果都不同，一半多报错，报错还都不一样

**Comment by lcl6679292** [comment]
> 特别是稳定性 比如我图片这个问题，问题不变，10次调用，结果都不同，一半多报错，报错还都不一样

您好，可以看下您的注册新工具那块是怎么写的吗，可以参考我们提供的notebook的方式来构建tool，可以尽量把描述部分详细一些

**Comment by lcl6679292** [comment]
> 同意上面说法，并且相对qwen-7B，好像缺少了stop_word的机制，会经常出现重复的现象 ![image](https://user-images.githubusercontent.com/29777487/267026887-a97e78e7-638f-467d-b75a-4948bb78f757.png)

您好，直接使用原始模型chat功能的话是会存在这个问题，因为您这边没有把模型生成的api请求去调用对应的模型服务，模型就容易出现幻觉，自己去生成执行部分结果。我们后面也会优化下模型，对于这种不拼接请求结果的生成及时停止生成

您可以用我们agent来尝试，agent会自动把模型生成的api请求去调用服务产生结果后，重新拼接给到大模型继续生成
https://github.com/modelscope/modelscope-agent/blob/master/demo/demo_qwen_agent.ipynb

**Comment by longerking** [comment]
> > 特别是稳定性 比如我图片这个问题，问题不变，10次调用，结果都不同，一半多报错，报错还都不一样
> 
> 您好，可以看下您的注册新工具那块是怎么写的吗，可以参考我们提供的notebook的方式来构建tool，可以尽量把描述部分详细一些 ![image](https://user-images.githubusercontent.com/22518743/267186032-1f64906b-fb38-4b94-a454-1cb9c38e112d.png)
> 
> https://github.com/modelscope/modelscope-agent/blob/master/demo/demo_register_new_tool.ipynb

您好，请问按照这里的方式注册新的tool后，如何给该tool配置对应的API接口呢？

**Comment by lcl6679292** [comment]
> > > 特别是稳定性 比如我图片这个问题，问题不变，10次调用，结果都不同，一半多报错，报错还都不一样
> > 
> > 
> > 您好，可以看下您的注册新工具那块是怎么写的吗，可以参考我们提供的notebook的方式来构建tool，可以尽量把描述部分详细一些 ![image](https://user-images.githubusercontent.com/22518743/267186032-1f64906b-fb38-4b94-a454-1cb9c38e112d.png)
> > https://github.com/modelscope/modelscope-agent/blob/master/demo/demo_register_new_tool.ipynb
> 
> 您好，请问按照这里的方式注册新的tool后，如何给该tool配置对应的API接口呢？

目前支持remote call和 local_call两种，如果你是要remote_call，那可以在这个新注册的class里面增加一个 """def __remote_call()"""，类似于基类里的这段代码

https://github.com/modelscope/modelscope-agent/blob/master/modelscope_agent/tools/tool.py#L69C4-L69C4

**Comment by xinwenhh** [comment]
<img width="789" alt="image" src="https://github.com/modelscope/modelscope-agent/assets/118965581/e6d9f83e-6d2c-4507-a311-d6117e0c3d72">
您好，我看目前的例子是提供这样调用工具，有没有调用API的例子。

**Comment by xinwenhh** [comment]
可以不调用modelscope远程的api，调用自己已经跑出的api吗

**Comment by xinwenhh** [comment]
您好想请问一下上图代码的这个位置是modelscope远程仓的路径吗，还是其他意思，他是怎么调用的
<img width="1427" alt="image" src="https://github.com/modelscope/modelscope-agent/assets/118965581/a9216ae6-0165-41e1-a55b-d765d753833f">

**Comment by xinwenhh** [comment]
> > > > 特别是稳定性 比如我图片这个问题，问题不变，10次调用，结果都不同，一半多报错，报错还都不一样
> > > 
> > > 
> > > 您好，可以看下您的注册新工具那块是怎么写的吗，可以参考我们提供的notebook的方式来构建tool，可以尽量把描述部分详细一些 ![image](https://user-images.githubusercontent.com/22518743/267186032-1f64906b-fb38-4b94-a454-1cb9c38e112d.png)
> > > https://github.com/modelscope/modelscope-agent/blob/master/demo/demo_register_new_tool.ipynb
> > 
> > 
> > 您好，请问按照这里的方式注册新的tool后，如何给该tool配置对应的API接口呢？
> 
> 目前支持remote call和 local_call两种，如果你是要remote_call，那可以在这个新注册的class里面增加一个 """def __remote_call()"""，类似于基类里的这段代码
> 
> https://github.com/modelscope/modelscope-agent/blob/master/modelscope_agent/tools/tool.py#L69C4-L69C4

可以举个小小的例子吗，看了很多天了，调用远程api依然没有思路

**Comment by wenmengzhou** [comment]
@xinwenhh 问题解决了吗？

**Comment by zzhangpurdue** [comment]
版本已经更新到0.3.0，可以尝试拉取最新版本进行试验。另外，超过4个月未反馈，关闭
