### ISSUE TITLE
预训练显存不够

### ISSUE THREAD

**Issue by timegoby** [modelscope/modelscope-agent#277]
训完一轮显示显存不够，一共4张16G的卡，有办法减小显存使用吗？
![企业微信截图_17056552306883](https://github.com/modelscope/modelscope-agent/assets/48506074/dfb4007d-0493-4ced-8bce-d68b388ff1c4)

![企业微信截图_1705655116808](https://github.com/modelscope/modelscope-agent/assets/48506074/c59b1670-7a16-423e-9b09-fb86c05a0672)

**Comment by mushenL** [comment]
您好，关于训练，您可以参考这个示例脚本https://github.com/tastelikefeet/swift/blob/feat/support_aigc_models/examples/pytorch/llm/scripts/qwen_7b_chat/qlora_ddp_ds/sft.sh
使用的是2*16G的环境，用的是qlora，可以显著优化显存不够的问题
