### ISSUE TITLE
如何在一次运行中多步调用工具？

### ISSUE THREAD

**Issue by Mike4Ellis** [modelscope/modelscope-agent#28]
很棒的工作～有几个问题想要咨询一下，望解答～

我理解目前的逻辑是，每次agent.run需要执行多次交互来获取最终结果，通常第一次交互是 用LLM提取工具的json参数信息(llm_result)，并调用插件返回执行结果(exec_result)，第二次交互是可以将这些信息一同交给LLM，使其整合信息给出标准语言的回复。

但是，这里面的多轮交互不涉及多步调用多个工具，比如当用户输入“请帮我计算2与3的和的5次方等于多少？”，尽管加法与幂运算的工具均存在，它也只会调用一个工具，给我返回2的5次方作为答案。

我的问题是，可否实现用户一次输入多步调用工具给出答案？如果暂时不可以，那么有什么成熟的方案可以拆分用户的输入，使其分步地给到agent吗？

期待您的回复～

**Comment by Zhikaiiii** [comment]
> 很棒的工作～有几个问题想要咨询一下，望解答～
> 
> 我理解目前的逻辑是，每次agent.run需要执行多次交互来获取最终结果，通常第一次交互是 用LLM提取工具的json参数信息(llm_result)，并调用插件返回执行结果(exec_result)，第二次交互是可以将这些信息一同交给LLM，使其整合信息给出标准语言的回复。
> 
> 但是，这里面的多轮交互不涉及多步调用多个工具，比如当用户输入“请帮我计算2与3的和的5次方等于多少？”，尽管加法与幂运算的工具均存在，它也只会调用一个工具，给我返回2的5次方作为答案。
> 
> 我的问题是，可否实现用户一次输入多步调用工具给出答案？如果暂时不可以，那么有什么成熟的方案可以拆分用户的输入，使其分步地给到agent吗？
> 
> 期待您的回复～

现在的代码`agent.run()`的核心部分，其实是有一个`while True`的循环，只有模型返回了summry 结果或者工具调用失败才会跳出循环直接返回。因此如果LLM有多步planning的能力的话，框架层面是支持多步调用工具的，所以这里应该是LLM本身的planning有点问题。

**Comment by Mike4Ellis** [comment]
> > 很棒的工作～有几个问题想要咨询一下，望解答～
> > 我理解目前的逻辑是，每次agent.run需要执行多次交互来获取最终结果，通常第一次交互是 用LLM提取工具的json参数信息(llm_result)，并调用插件返回执行结果(exec_result)，第二次交互是可以将这些信息一同交给LLM，使其整合信息给出标准语言的回复。
> > 但是，这里面的多轮交互不涉及多步调用多个工具，比如当用户输入“请帮我计算2与3的和的5次方等于多少？”，尽管加法与幂运算的工具均存在，它也只会调用一个工具，给我返回2的5次方作为答案。
> > 我的问题是，可否实现用户一次输入多步调用工具给出答案？如果暂时不可以，那么有什么成熟的方案可以拆分用户的输入，使其分步地给到agent吗？
> > 期待您的回复～
> 
> 现在的代码`agent.run()`的核心部分，其实是有一个`while True`的循环，只有模型返回了summry 结果或者工具调用失败才会跳出循环直接返回。因此如果LLM有多步planning的能力的话，框架层面是支持多步调用工具的，所以这里应该是LLM本身的planning有点问题。

感谢您的回复，我明白了。那么如果要解决这个问题，是要训练出更强大、更适合作为Agent大脑的LLM是吗？我理解目前的瓶颈就是LLM的能力了。

**Comment by lcl6679292** [comment]
> 

对，是的，这里可能是模型多步规划泛化能力还是不够，您可以继续基于我们提供的开源模型做微调训练，来进一步增强大模型在特定场景多步指令调用的能力

**Comment by Mike4Ellis** [comment]
好的，十分感谢～
