### ISSUE TITLE
急急急！使用本地向量库时，报一个告警，且最后调用agent输出时候出错了，没有结果

### ISSUE THREAD

**Issue by JsDoingYJ** [modelscope/modelscope-agent#280]
![QQ图片20240121114446](https://github.com/modelscope/modelscope-agent/assets/51501040/315b93b5-9b9b-473f-b22c-5e38023d61a0)
前面的，向量数据库和Flashatten的警告，是不是代表没有初始化成功，我看后面，调用agent.run 是直接在第一个try catch跳出来了，返回了
求大佬解答一下？

**Comment by mushenL** [comment]
您好，可以提供一下您的运行代码，我这边复现一下

**Comment by mushenL** [comment]
您好，根据您的报错信息，以及我本地调试的结果，原因应该是您尝试在CPU上执行矩阵乘法操作时遇到了一个问题，因为所使用的数据类型是Half，也就是16位浮点数（通常称为半精度浮点数），如果您的CPU没有专用数学库支持的CPU环境，对Half数据类型的运算无法实现，这边建议您使用GPU的环境进行推理
