### ISSUE TITLE
关于AgentFabric和ModelScope的Bug

### ISSUE THREAD

**Issue by Runyu-Zhou05** [modelscope/modelscope-agent#282]
1.
![image](https://github.com/modelscope/modelscope-agent/assets/149618011/db1a147f-f055-4b60-b03f-87d0cec9d48c)
我发现此处点击上传文件是上传到知识库里面了，而不是上传给模型。

2. 勾选了Web Browsing和Web Searching，但模型还说他无法访问互联网。发布到创空间的时候提供了Bing Search v7的API Key，还是不行。

3. 我想请问怎么使用阿里云灵积的PDF解析插件呢？我想让Agent支持PDF解析的功能。或者你们能否做一个PDF解析的Tool呢？

**Comment by Runyu-Zhou05** [comment]
1和2解决了，选中工具后忘记点更新配置了（
不过3还是没有解决

**Comment by Runyu-Zhou05** [comment]
此外，在ModelScope的网站UI上，Agent调用完API后结果会一个字一个字的打印出来，Web Search的返回JSON一般都特别长，导致这个地方得等好久，能不能修一下？

**Comment by mushenL** [comment]
您好，关于问题3，可以本地从apps/agentfabric 运行python app.py在本地拉起您使用的界面，具体如何自定义tool可以参考demo/demo_register_new_tool.ipynb文件在本地添加相关的tool，如果想在创空间的官方工具上使用您自定义的tool，欢迎在github上提pr来共享您的tool，相应的我们会在创空间上更新，关于Web Search的返回JSON过长的问题，我们在后面的版本会相应的优化，感谢您的反馈

**Comment by Runyu-Zhou05** [comment]
谢谢！不过我说的不是“Web Search的返回JSON过长的问题”，而是有时候输出过长必须等它一个字一个字的显示出来（即便推理或API调用已经完成了），浪费时间的问题。我觉得这是一个网站UI的问题

**Comment by mushenL** [comment]
您好，关于这个问题，您可以运行apps/agentfabric下的app.py在本地拉起界面，在下图所示的位置中，加入flushing_speed的参数调整文本的生成速度，范围为1至10，默认值为5，创空间的官方工具目前是按照默认值进行，已经进行了反馈，后续版本会进行相应调整
![2024-01-25_17-45-41](https://github.com/modelscope/modelscope-agent/assets/125954878/3a856ef0-9949-4419-a1f9-3d03e1d64c89)

**Comment by Runyu-Zhou05** [comment]
好的，谢谢！
