### ISSUE TITLE
目前ModelScope-Agent支持的模型有哪些？

### ISSUE THREAD

**Issue by DirtyKnightForVi** [modelscope/modelscope-agent#285]
如题。

**Comment by mushenL** [comment]
https://modelscope.cn/studios/modelscope/AgentFabric/summary

**Comment by mushenL** [comment]
https://modelscope.cn/studios/modelscope/AgentFabric/summary
您可以访问这个网址体验Agent的相关功能，也包含了先版本支持并推荐的模型

**Comment by DirtyKnightForVi** [comment]
> https://modelscope.cn/studios/modelscope/AgentFabric/summary 您可以访问这个网址体验Agent的相关功能，也包含了先版本支持并推荐的模型

谢谢。

请问agent.llm 的factory，有加载本地模型的样例代码吗？这是一个特殊的需求，因为是内网环境。

**Comment by mushenL** [comment]
您好，加载模型可以参考demo路径下的示例代码，如果想加载本地模型的话，需要将model id替换为您的模型的本地路径即可

**Comment by mushenL** [comment]
新版本关于调用本地模型，可以参考https://github.com/modelscope/modelscope-agent/pull/307/files 中的关于无外网环境部署方案的示例
