### ISSUE TITLE
想问config为什么要默认放在/tmp/agentfabric/config/local_user/builder_config.json下？

### ISSUE THREAD

**Issue by Mally-cj** [modelscope/modelscope-agent#286]
在本地修改json的时候，发现上传到创空间没有效果，是因为config要默认放在/tmp/agentfabric/config/local_user/builder_config.json下，想问为什么这么设计呢？不直接放在项目目录下？

**Comment by mushenL** [comment]
您好，关于您说的问题，路径的设置我们一般是出于安全性，避免项目污染，同时遵循着配置分离的原则，/tmp 目录通常用于存放临时文件，系统可能对这个目录有特殊的权限管理，如果您需要对上传至创空间并且配置文件生效，需要按照您的需求对config的位置进行设置，根据代码变更默认存放路径，关于您说的问题我们会在后期版本中在文档上进行详细说明
