### ISSUE TITLE
支持定义一些输入更复杂，功能更多的工具吗？

### ISSUE THREAD

**Issue by CaC033** [modelscope/modelscope-agent#296]
比如让大模型直接提取需要提取的信息进一个不定长的列表之类的？或者能在工具中动态维护一个列表？

**Comment by wenmengzhou** [comment]
可以在工具中维护这个列表

**Comment by CaC033** [comment]
> 可以在工具中维护这个列表

我想问一下,如果我需要自定义两个工具,第一个工具用于读取数据并且向这个列表中添加数据,另一个工具用于对这个列表中的数据进行计算.这种情况应该如何定义呢? 我理解每个工具都是继承于Tool类并且用_local_call进行执行,所以每个操作都因该单独定义一个工具类进行,但是如果用其中一个tool维护列表,另一个tool用于计算的话,在定义的时候维护列表的tool是没有实例化的, 这样就不能在定义的时候把用于把用于维护列表的工具的实例传入用于操作的工具. 目前我的做法是维护一个文件,文件内保存这个列表数据,但是考虑到需求上线可能会有并行推理, 这样不同的输入之间可能会互相产生干扰么?

**Comment by CaC033** [comment]
> 可以在工具中维护这个列表

我的表达可能有些太啰嗦了,你可以理解为我想问一下,框架支持自定义的两个或两个以上的工具情况下,可以让某个工具实例化之后默认作为另一个工具实例化时的输入么? 或者有没有什么替代的解决方案.

**Comment by wenmengzhou** [comment]
这个目前不太可以，每个工具目前假设是原子化可以独立完成的操作， 可以考虑有一个共同的数据参数，分别传给不同的工具，然后根据这个数据参数去读取文件/redis等存储系统上的数据进行处理，可以完成你说的两个工具分开处理数据的能力，但是每次处理前后都需要读取保存对应数据

**Comment by CaC033** [comment]
> 这个目前不太可以，每个工具目前假设是原子化可以独立完成的操作， 可以考虑有一个共同的数据参数，分别传给不同的工具，然后根据这个数据参数去读取文件/redis等存储系统上的数据进行处理，可以完成你说的两个工具分开处理数据的能力，但是每次处理前后都需要读取保存对应数据

目前框架能支持让千问自动化的提取固定格式的字典作为输入么? 举个例子,我需要提取对话中的物品以及物品的长度信息, 按照示例中的做法我需要定义两个入参,一个为物品的名称,另一个为物品的长度, 模型会执行多个action来提取多个物品的信息. 框架可以支持在第一个action时就把多个入参以字典的形式提取好么? 这样也能一定程度的解决这个问题

**Comment by wenmengzhou** [comment]
这个是可以的，你通过prompt可以来完成这样的事情
