### ISSUE TITLE
更新代码后，官方的modelscope-agent-7b 无法运行了，有新的方法吗？

### ISSUE THREAD

**Issue by whk6688** [modelscope/modelscope-agent#298]
model_name = 'modelscope-agent-7b'
model_cfg = {
    'modelscope-agent-7b':{
        'type': 'modelscope',
        'model_id': 'damo/ModelScope-Agent-7B',
        'model_revision': 'v1.0.0',
        'use_raw_generation_config': True,
        'custom_chat': True
    }
}

tool_cfg_file = os.getenv('TOOL_CONFIG_FILE', 'config/cfg_tool_template.json')
tool_cfg = Config.from_file(tool_cfg_file)

llm = LLMFactory.build_llm(model_name, model_cfg)

**Comment by mushenL** [comment]
`from modelscope_agent.llm import get_chat_model
llm_config = {'model': 'iic/ModelScope-Agent-7B', 'model_server': 'modelscope','model_version':'v1.0.4'}
llm = get_chat_model(**llm_config)`
可以尝试更新到v0.3版本，本地调用的情况可以参考以上代码

**Comment by mushenL** [comment]
from modelscope_agent.llm import get_chat_model
llm_config = {'model': 'iic/ModelScope-Agent-7B', 'model_server': 'modelscope','model_version':'v1.0.4'}
llm = get_chat_model(**llm_config)
可以尝试更新到v0.3版本，本地调用的情况可以参考以上代码
