### ISSUE TITLE
readme中的示例不可用

### ISSUE THREAD

**Issue by CaC033** [modelscope/modelscope-agent#309]
import os
from modelscope.utils.config import Config
from modelscope_agent.llm import LLMFactory
from modelscope_agent.agent import AgentExecutor

model_name = 'modelscope-agent-7b'
model_cfg = {
  'modelscope-agent-7b': {
    'type': 'modelscope',
    'model_id': 'damo/ModelScope-Agent-7B',
    'model_revision': 'v1.0.0',
    'use_raw_generation_config': True,
    'custom_chat': True
  }
}

tool_cfg_file = os.getenv('TOOL_CONFIG_FILE', 'config/cfg_tool_template.json')
tool_cfg = Config.from_file(tool_cfg_file)

llm = LLMFactory.build_llm(model_name, model_cfg)
agent = AgentExecutor(llm, tool_cfg)

这段示例在最新的代码中已经不可用了，会报错：

ImportError: cannot import name 'LLMFactory' from 'modelscope_agent.llm' (/mnt/workspace/modelscope-agent/demo/../modelscope_agent/llm/__init__.py)

希望更新一下调取本地模型的用例

**Comment by mushenL** [comment]
您好，关于中文readme上的部分代码在最新版本中不适用，我们会尽快对中文readme进行更新，建议先参考[英文readme.md](https://github.com/modelscope/modelscope-agent/blob/master/README.md)进行部署，关于您说的调用本地模型，可以参考https://github.com/modelscope/modelscope-agent/pull/307/files 中的关于无外网环境部署方案的示例

**Comment by CaC033** [comment]
> 您好，关于中文readme上的部分代码在最新版本中不适用，我们会尽快对中文readme进行更新，建议先参考[英文readme.md](https://github.com/modelscope/modelscope-agent/blob/master/README.md)进行部署，关于您说的调用本地模型，可以参考https://github.com/modelscope/modelscope-agent/pull/307/files 中的关于无外网环境部署方案的示例

请问能像中文readme的那个不可用的例子一样，以qwen agent模型为例子写一个简单的用例吗？英文readme.md中的例子并没有提供直接可用的例子，对想快速上手运用的开发者并不太友好。

**Comment by mushenL** [comment]
https://github.com/modelscope/modelscope-agent/pull/307/files
您好，这个就是关于本地部署的例子，里面有详细的部署方案，现在modelscope-agent的本地部署推荐的是modelscope提供的官方部署方法，之前的方法有较多缺陷，现在的方案更容易上手
