### ISSUE TITLE
'Message': '获取模型版本失败，信息：获取模失败',

### ISSUE THREAD

**Issue by kevin2016** [modelscope/modelscope-agent#31]
'Message': '获取模型版本失败，信息：获取模失败',

**Comment by lcl6679292** [comment]
您好，问题已经修复了，请拉取最新代码再次尝试

**Comment by kevin2016** [comment]
> 您好，问题已经修复了，请拉取最新代码再次尝试

我这边的报错信息是：HTTPError: 404 Client Error: Not Found for url: http://www.modelscope.cn/api/v1/models/damo/MSAgent-Qwen-7B/revisions?EndTime=1694682870

**Comment by lcl6679292** [comment]
> > 您好，问题已经修复了，请拉取最新代码再次尝试
> 
> 我这边的报错信息是：HTTPError: 404 Client Error: Not Found for url: http://www.modelscope.cn/api/v1/models/damo/MSAgent-Qwen-7B/revisions?EndTime=1694682870

请拉取最新的代码，我们已经更换了模型

![image](https://github.com/modelscope/modelscope-agent/assets/22518743/395965d6-474a-4a7d-8f34-cdc1458b5039)
