### ISSUE TITLE
run errors: from modelscope_agent.agent import AgentExecutor, there is  no  AgentExecutor

### ISSUE THREAD

**Issue by BoxFishLab** [modelscope/modelscope-agent#313]
![image](https://github.com/modelscope/modelscope-agent/assets/22937526/44b0f2b4-5afc-455f-bfaa-9dcb8a99b606)
from modelscope_agent.agent import AgentExecutor
ImportError: cannot import name 'AgentExecutor' from 'modelscope_agent.agent'

**Comment by mushenL** [comment]
您好，这边建议您使用apps/agentfabric/app.py的方式来部署agent界面，apps/msgpt/app.py中的部分依赖在新版本中已经弃用，我们在后续版本会进行优化

**Comment by zzclynn** [comment]
modelscope-agent新版本目前更新较大，msgpt这个实例，我们后续会更新至最新版本
