### ISSUE TITLE
使用glm4运行test_image_gen.py出现的问题，请问如何解决

### ISSUE THREAD

**Issue by Guodashen222** [modelscope/modelscope-agent#315]
将def test_image_gen_role函数中的llm_config设置为glm4
def test_image_gen_role():
    role_template = '你扮演一个画家，用尽可能丰富的描述调用工具绘制图像。'

    # llm_config = {'model': 'qwen-max', 'model_server': 'dashscope'}
    llm_config = {'model': 'glm-4', 'model_server': 'zhipu'}

    # input tool args
    function_list = ['image_gen']

    bot = RolePlay(
        function_list=function_list, llm=llm_config, instruction=role_template)

    response = bot.run('画一张猫的图像')

    text = ''
    for chunk in response:
        text += chunk
    print(text)
    assert isinstance(text, str)
    
    运行结果：
    (ms_agent) (base) guo@guo:~/modelscope-agent/tests/tools$ python test_image_gen.py 
2024-02-28 18:19:21,261 - modelscope - INFO - PyTorch version 2.2.1+cpu Found.
2024-02-28 18:19:21,261 - modelscope - INFO - Loading ast index from /home/guo/.cache/modelscope/ast_indexer
2024-02-28 18:19:21,278 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 44bb933a7276847a22a2d5451fd2144d and a total number of 964 components indexed
====> stream messages: [{'role': 'system', 'content': '\n# 指令\n\n你扮演一个画家，用尽可能丰富的描述调用工具绘制图像。\n\n请注意：你具有图像和视频的展示能力，也具有运行代码的能力，不要在回复中说你做不到。\n'}, {'role': 'user', 'content': '画一张猫的图像'}]
tool_call: index=0 id='call_8426537302949106376' function=ChoiceDeltaToolCallFunction(arguments='{"resolution":"1024*1024","text":"一只可爱的猫咪，毛茸茸的，大眼睛，分辨率1024*1024，高清，柔和的色彩，艺术家维多利亚·弗朗西斯。"}', name='image_gen') type='function'
Traceback (most recent call last):
  File "/home/guo/modelscope-agent/tests/tools/test_image_gen.py", line 39, in <module>
    test_image_gen_role()
  File "/home/guo/modelscope-agent/tests/tools/test_image_gen.py", line 35, in test_image_gen_role
    for chunk in response:
  File "/home/guo/modelscope-agent/modelscope_agent/agents/role_play.py", line 238, in _run
    use_tool, action, action_input, output = self._detect_tool(
  File "/home/guo/modelscope-agent/modelscope_agent/agents/role_play.py", line 264, in _detect_tool
    assert isinstance(message, str)
AssertionError

**Comment by Guodashen222** [comment]
以及在test_weather.py中，将lm_config设置为glm4也会有同样的问题。通过修改RolePlay中的def _detect_tool函数可以正常使用。
修改如下：
def _detect_tool(self, message: Union[str,
                                          dict]) -> Tuple[bool, str, str, str]:
        action = message['function_call']['name']
        action_input = message['function_call']['arguments']
        message = f"Action: {action}\nAction Input: {action_input}"
        assert isinstance(message, str)
        text = message
        func_name, func_args = None, None
        i = text.rfind(ACTION_TOKEN)
        j = text.rfind(ARGS_TOKEN)
        k = text.rfind(OBSERVATION_TOKEN)
        if 0 <= i < j:  # If the text has `Action` and `Action input`,
            if k < j:  # but does not contain `Observation`,
                # then it is likely that `Observation` is ommited by the LLM,
                # because the output text may have discarded the stop word.
                text = text.rstrip() + OBSERVATION_TOKEN  # Add it back.
            k = text.rfind(OBSERVATION_TOKEN)
            func_name = text[i + len(ACTION_TOKEN):j].strip()
            func_args = text[j + len(ARGS_TOKEN):k].strip()
            text = text[:k]  # Discard '\nObservation:'.

        return (func_name is not None), func_name, func_args, text

**Comment by Guodashen222** [comment]
以及在test_weather.py中，将lm_config设置为glm4也会有同样的问题。通过修改RolePlay中的def _detect_tool函数可以正常使用。
修改如下：
def _detect_tool(self, message: Union[str,
                                          dict]) -> Tuple[bool, str, str, str]:
        action = message['function_call']['name']
        action_input = message['function_call']['arguments']
        message = f"Action: {action}\nAction Input: {action_input}"
        assert isinstance(message, str)
        text = message
        func_name, func_args = None, None
        i = text.rfind(ACTION_TOKEN)
        j = text.rfind(ARGS_TOKEN)
        k = text.rfind(OBSERVATION_TOKEN)
        if 0 <= i < j:  # If the text has `Action` and `Action input`,
            if k < j:  # but does not contain `Observation`,
                # then it is likely that `Observation` is ommited by the LLM,
                # because the output text may have discarded the stop word.
                text = text.rstrip() + OBSERVATION_TOKEN  # Add it back.
            k = text.rfind(OBSERVATION_TOKEN)
            func_name = text[i + len(ACTION_TOKEN):j].strip()
            func_args = text[j + len(ARGS_TOKEN):k].strip()
            text = text[:k]  # Discard '\nObservation:'.

        return (func_name is not None), func_name, func_args, text

**Comment by Guodashen222** [comment]
还有一个问题 运行modelscope-agent/apps/agentfabric/app.py的时候 应该如何设置tool？ 我不能正常调用mage_gen和高德的天气工具

**Comment by mushenL** [comment]
您好，关于运行modelscope-agent/apps/agentfabric/app.py的时候应该如何设置tool的问题，当您部署之后，可视化页面上有相应的tool配置选项，修改之后点击更新配置即可，具体的个人配置文件路径一般在/tmp/agentfabric/xxx 下，您可以按需修改，关于您说的报错这边正在看，后续会进行修复
