### ISSUE TITLE
dashscope上没有通义千问7b trial apply的申请入口。

### ISSUE THREAD

**Issue by Orlando1021** [modelscope/modelscope-agent#32]
Apply to activate the DashScope service, go to 模型广场 -> 通义千问开源系列 -> apply for a trial of 通义千问7B. The free quota is 100,000 tokens. 这条道路并走不通。没有申请试用入口，acess denied.

**Comment by lcl6679292** [comment]
您好，这个api申请入口因一些故障暂时停止了，恢复后我们会第一时间通知
