### ISSUE TITLE
请问得到工具输出的结果后，拼接prompt的role角色是什么？

### ISSUE THREAD

**Issue by MGzhou** [modelscope/modelscope-agent#326]
请问得到工具输出的结果后，拼接prompt的role角色是 user 还是 assistant。

**Comment by mushenL** [comment]
您好，一般工具输入的时候是user，输出的时候显示的是assistant，您可以在 demo/demo_modelscopegpt_agent.ipynb 这个demo文件上尝试运行一下，拼接的prompt会显示出来

**Comment by MGzhou** [comment]
好的，谢谢。
