### ISSUE TITLE
agent无法自动循环

### ISSUE THREAD

**Issue by surviveMiao** [modelscope/modelscope-agent#330]
如何使agent自动停止回答？
当问agent一个问题时，可能第一轮就已经得到了答案，但是此时的action 仍然有值，不为None， 就这样重复的调用了两三次agent，生成的都是相同的答案，才会自己停止。
如何在agent第一次生成答案的时候 就停止循环呢？

**Comment by mushenL** [comment]
您好，这种一般情况下是模型效果的问题，部分模型需要针对agent进行微调适配，建议您可以使用调用qwen-max等推荐模型进行推理试试？

**Comment by surviveMiao** [comment]
好的谢谢
