### ISSUE TITLE
是否可以提供更多的example?

### ISSUE THREAD

**Issue by douyh** [modelscope/modelscope-agent#353]
### Description

在demo文件夹下面，看到的似乎都是使用qwen-max模型的例子，收否可以提供更多的例子，比如调用openai和modelscope模型如何调用（比如qwen-7B），  `_chat_stream` 方法没有实现，`_chat_no_stream`如何使用是否有一些例子？ 

另外在readme中看到了一些关于调用本地模型的例子，但是好像已经不能用了，LLMFactory这个class在代码中似乎已经没有了？
![image](https://github.com/modelscope/modelscope-agent/assets/34704737/01278840-4fe1-49ea-9b4c-7b3eabf0a4a7)

万分感谢

**Comment by zzhangpurdue** [comment]
感谢，你的反馈，关于例子我们有版本更新，你看的是中文版本的readme中确实没有更新，请先参考英文文档，我立刻更新。
另外，调用小模型的例子目前采用的是vllm的方案，用户可以本地部署vllm模型拉起，具体参考：https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md
可以参考本地部署的文档，将模型部署成服务的方式。

同时，我们也会持续增加使用case。

**Comment by XduSyL** [comment]
> 感谢，你的反馈，关于例子我们有版本更新，你看的是中文版本的readme中确实没有更新，请先参考英文文档，我立刻更新。 另外，调用小模型的例子目前采用的是vllm的方案，用户可以本地部署vllm模型拉起，具体参考：https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md 可以参考本地部署的文档，将模型部署成服务的方式。
> 
> 同时，我们也会持续增加使用case。

那这样的话是不是会麻烦很多，请问以后是否还会采用像LLMfactory这样的类来管理呢？

**Comment by zzhangpurdue** [comment]
readme已经更新，另外LLMfactory的类，我们目前没有维护不过有一个LLM_REGISTRY，模型注册中心，方便后续新增模型。
目前agent能力较好的模型还不是很多，后续躲起来的话，用这个方法也可以快速注册起来。

**Comment by douyh** [comment]
> 感谢，你的反馈，关于例子我们有版本更新，你看的是中文版本的readme中确实没有更新，请先参考英文文档，我立刻更新。 另外，调用小模型的例子目前采用的是vllm的方案，用户可以本地部署vllm模型拉起，具体参考：https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md 可以参考本地部署的文档，将模型部署成服务的方式。
> 
> 同时，我们也会持续增加使用case。

感谢你的回复。我这里的需求应该没有这么复杂，也不需要gradio的UI，只是想使用modelscope上已有的模型，比如Qwen-7B之类的，通过直接下载的方式将模型下载到本地（这个是可以完成的），然后跑一个简单的比如天气查询或者图像生成之类的任务。现在看起来modelscope上的模型因为没有实现`_chat_stream`方法而没有办法运行。

**Comment by douyh** [comment]
> 感谢，你的反馈，关于例子我们有版本更新，你看的是中文版本的readme中确实没有更新，请先参考英文文档，我立刻更新。 另外，调用小模型的例子目前采用的是vllm的方案，用户可以本地部署vllm模型拉起，具体参考：https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md 可以参考本地部署的文档，将模型部署成服务的方式。
> 
> 同时，我们也会持续增加使用case。

![image](https://github.com/modelscope/modelscope-agent/assets/34704737/a95c32e9-b443-449c-a823-ca0a6a5492ef)

根据参考文档中的内容，部署了Qwen1.5-7B-chat. 发现qwen_vllm分支还有一个这样的bug。OBSERVATION_TOKEN后面有一个多余的冒号，导致k=-1，然后在已经有`Observation`的情况下会继续加上一个`Observation:`

![image](https://github.com/modelscope/modelscope-agent/assets/34704737/dc3c0f43-d45d-45e9-9059-4a0c253ef026)

![image](https://github.com/modelscope/modelscope-agent/assets/34704737/d4beb0ef-0b86-4fb7-ab0f-82ee861dfd16)

**Comment by zzhangpurdue** [comment]
> > 感谢，你的反馈，关于例子我们有版本更新，你看的是中文版本的readme中确实没有更新，请先参考英文文档，我立刻更新。 另外，调用小模型的例子目前采用的是vllm的方案，用户可以本地部署vllm模型拉起，具体参考：https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md 可以参考本地部署的文档，将模型部署成服务的方式。
> > 同时，我们也会持续增加使用case。
> 
> 感谢你的回复。我这里的需求应该没有这么复杂，也不需要gradio的UI，只是想使用modelscope上已有的模型，比如Qwen-7B之类的，通过直接下载的方式将模型下载到本地（这个是可以完成的），然后跑一个简单的比如天气查询或者图像生成之类的任务。现在看起来modelscope上的模型因为没有实现`_chat_stream`方法而没有办法运行。

主要是之前modelscope上的模型没有stream的返回，所以我们没支持，如果你有需求的话，我们可以快速看一下。怎么加起来。

**Comment by zzhangpurdue** [comment]
> > 感谢，你的反馈，关于例子我们有版本更新，你看的是中文版本的readme中确实没有更新，请先参考英文文档，我立刻更新。 另外，调用小模型的例子目前采用的是vllm的方案，用户可以本地部署vllm模型拉起，具体参考：https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md 可以参考本地部署的文档，将模型部署成服务的方式。
> > 同时，我们也会持续增加使用case。
> 
> ![image](https://private-user-images.githubusercontent.com/34704737/313952716-a95c32e9-b443-449c-a823-ca0a6a5492ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2MjksIm5iZiI6MTcxMDgzNzMyOSwicGF0aCI6Ii8zNDcwNDczNy8zMTM5NTI3MTYtYTk1YzMyZTktYjQ0My00NDljLWE4MjMtY2EwYTZhNTQ5MmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMzA5Y2QzMDIzZmE2M2I1YTZhMzMyMjcyNzY4ZDhjMDRhMDkxMzJhYzIyMTE1MDU2MjNkODk2YjIzNjExODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LnzU61cGqVIluNumOEXpsdZeyIlZ6XHOwlkmODdjbfE)
> 
> 根据参考文档中的内容，部署了Qwen1.5-7B-chat. 发现qwen_vllm分支还有一个这样的bug。OBSERVATION_TOKEN后面有一个多余的冒号，导致k=-1，然后在已经有`Observation`的情况下会继续加上一个`Observation:`
> 
> ![image](https://private-user-images.githubusercontent.com/34704737/313953510-dc3c0f43-d45d-45e9-9059-4a0c253ef026.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2MjksIm5iZiI6MTcxMDgzNzMyOSwicGF0aCI6Ii8zNDcwNDczNy8zMTM5NTM1MTAtZGMzYzBmNDMtZDQ1ZC00NWU5LTkwNTktNGEwYzI1M2VmMDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MGQ5MzM1NDljYWEzNjA5MzJlMzMzMThmYjE4MGU1ODU4MTk1MTM4ZThmZDIzZWM3YmNlN2EzNWU0YjRkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YKm-mp3viz1rV3r-Qo9qt3JwEGHbF5cnJFyruoio8s4)
> 
> ![image](https://private-user-images.githubusercontent.com/34704737/313953273-d4beb0ef-0b86-4fb7-ab0f-82ee861dfd16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2MjksIm5iZiI6MTcxMDgzNzMyOSwicGF0aCI6Ii8zNDcwNDczNy8zMTM5NTMyNzMtZDRiZWIwZWYtMGI4Ni00ZmI3LWFiMGYtODJlZTg2MWRmZDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjY2Q5ZmE5ZDE3ZWVmNTBlNmFiZDRjMmM0MTMyNWQ5YzY1YzUxMjRlZGVlOGExOTNiNDFlYTg0MTc4NDQyMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b07QK3wPwHEjrjmPtWtg4uMaQwD_jtz_jUZzLVXw3-o)

收到，感谢反馈，我们这边跟进一下。

**Comment by Firmament-cyou** [comment]
> > 感谢，你的反馈，关于例子我们有版本更新，你看的是中文版本的readme中确实没有更新，请先参考英文文档，我立刻更新。 另外，调用小模型的例子目前采用的是vllm的方案，用户可以本地部署vllm模型拉起，具体参考：https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md 可以参考本地部署的文档，将模型部署成服务的方式。
> > 同时，我们也会持续增加使用case。
> 
> 感谢你的回复。我这里的需求应该没有这么复杂，也不需要gradio的UI，只是想使用modelscope上已有的模型，比如Qwen-7B之类的，通过直接下载的方式将模型下载到本地（这个是可以完成的），然后跑一个简单的比如天气查询或者图像生成之类的任务。现在看起来modelscope上的模型因为没有实现`_chat_stream`方法而没有办法运行。

您好，modelscope 为接入了 llm_pipeline 的模型提供了统一的流失输出方案，以下是一个调用示例：

```python
from modelscope import pipeline

input_messages = {
    'messages': [{
        'role': 'system',
        'content': '你是一个生活助手机器人。'
    }, {
        'role': 'user',
        'content': '你是谁？介绍一下你自己'
    }]
}

pipe = pipeline(task='chat', model='qwen/Qwen1.5-1.8B-Chat', llm_first=True) # llm_first 参数优先 llm_pipeline 构造
for stream_output in pipe.stream_generate(input_messages, do_sample=True, max_length=512):
    print(stream_output)
```

**Comment by douyh** [comment]
> > > 感谢，你的反馈，关于例子我们有版本更新，你看的是中文版本的readme中确实没有更新，请先参考英文文档，我立刻更新。 另外，调用小模型的例子目前采用的是vllm的方案，用户可以本地部署vllm模型拉起，具体参考：https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md 可以参考本地部署的文档，将模型部署成服务的方式。
> > > 同时，我们也会持续增加使用case。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/34704737/313952716-a95c32e9-b443-449c-a823-ca0a6a5492ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2MjksIm5iZiI6MTcxMDgzNzMyOSwicGF0aCI6Ii8zNDcwNDczNy8zMTM5NTI3MTYtYTk1YzMyZTktYjQ0My00NDljLWE4MjMtY2EwYTZhNTQ5MmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMzA5Y2QzMDIzZmE2M2I1YTZhMzMyMjcyNzY4ZDhjMDRhMDkxMzJhYzIyMTE1MDU2MjNkODk2YjIzNjExODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LnzU61cGqVIluNumOEXpsdZeyIlZ6XHOwlkmODdjbfE)
> > 根据参考文档中的内容，部署了Qwen1.5-7B-chat. 发现qwen_vllm分支还有一个这样的bug。OBSERVATION_TOKEN后面有一个多余的冒号，导致k=-1，然后在已经有`Observation`的情况下会继续加上一个`Observation:`
> > ![image](https://private-user-images.githubusercontent.com/34704737/313953510-dc3c0f43-d45d-45e9-9059-4a0c253ef026.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2MjksIm5iZiI6MTcxMDgzNzMyOSwicGF0aCI6Ii8zNDcwNDczNy8zMTM5NTM1MTAtZGMzYzBmNDMtZDQ1ZC00NWU5LTkwNTktNGEwYzI1M2VmMDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MGQ5MzM1NDljYWEzNjA5MzJlMzMzMThmYjE4MGU1ODU4MTk1MTM4ZThmZDIzZWM3YmNlN2EzNWU0YjRkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YKm-mp3viz1rV3r-Qo9qt3JwEGHbF5cnJFyruoio8s4)
> > ![image](https://private-user-images.githubusercontent.com/34704737/313953273-d4beb0ef-0b86-4fb7-ab0f-82ee861dfd16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc2MjksIm5iZiI6MTcxMDgzNzMyOSwicGF0aCI6Ii8zNDcwNDczNy8zMTM5NTMyNzMtZDRiZWIwZWYtMGI4Ni00ZmI3LWFiMGYtODJlZTg2MWRmZDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjY2Q5ZmE5ZDE3ZWVmNTBlNmFiZDRjMmM0MTMyNWQ5YzY1YzUxMjRlZGVlOGExOTNiNDFlYTg0MTc4NDQyMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b07QK3wPwHEjrjmPtWtg4uMaQwD_jtz_jUZzLVXw3-o)
> 
> 收到，感谢反馈，我们这边跟进一下。

关于这个bug，我尝试手动加上一个冒号，可以解决这个问题，完成一个工具的调用。但是如果我需要连续调用2个工具。比如我先尝试使用一个API获取某张车辆图片的型号（或者某个城市的天气），然后再将其转换为语音。我使用`Qwen1.5-7B-chat`或者`gpt-3.5-turbo` 都可以完成第一个工具调用。

第一轮的`planning_prompt`为空，并且调用了车型识别（或者天气查询）工具，得到了正确的结果；
第二轮的`planning_prompt`是类似如下的内容：
```python
'好的，我将使用`vehicle_type`工具来识别图片中的车辆品牌，然后使用`speech-generation`工具将结果转换为语音。\nAction: vehicle_type\nAction Input: {"img_path": "vehicle.jpg"}\n\nObservation: <result>The vehicle type is 宝马3系 produced in 2023, and the vehicle color is 蓝色</result>\nAnswer:'
```
**但是第二轮调用的工具却不会更新。**

**Comment by douyh** [comment]
> > > 感谢，你的反馈，关于例子我们有版本更新，你看的是中文版本的readme中确实没有更新，请先参考英文文档，我立刻更新。 另外，调用小模型的例子目前采用的是vllm的方案，用户可以本地部署vllm模型拉起，具体参考：https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md 可以参考本地部署的文档，将模型部署成服务的方式。
> > > 同时，我们也会持续增加使用case。
> > 
> > 
> > 感谢你的回复。我这里的需求应该没有这么复杂，也不需要gradio的UI，只是想使用modelscope上已有的模型，比如Qwen-7B之类的，通过直接下载的方式将模型下载到本地（这个是可以完成的），然后跑一个简单的比如天气查询或者图像生成之类的任务。现在看起来modelscope上的模型因为没有实现`_chat_stream`方法而没有办法运行。
> 
> 您好，modelscope 为接入了 llm_pipeline 的模型提供了统一的流式输出方案，以下是一个调用示例：
> 
> ```python
> from modelscope import pipeline
> 
> input_messages = {
>     'messages': [{
>         'role': 'system',
>         'content': '你是一个生活助手机器人。'
>     }, {
>         'role': 'user',
>         'content': '你是谁？介绍一下你自己'
>     }]
> }
> 
> pipe = pipeline(task='chat', model='qwen/Qwen1.5-1.8B-Chat', llm_first=True) # llm_first 参数优先 llm_pipeline 构造
> for stream_output in pipe.stream_generate(input_messages, do_sample=True, max_length=512):
>     print(stream_output)
> ```

请问是需要按照这个内容新增到`_chat_stream`的实现中吗？我先试试看。

**Comment by XduSyL** [comment]
请问一下在demo/demo_qwen_agent.ipynb的demo中，如果我要与大模型进行多轮会话的话要怎么操作呀，因为，我看RolePlay这个类实例化之后，每次执行run函数都会将self.query_prefix置为空。

**Comment by zzhangpurdue** [comment]
通过history传递上一轮的输出，作为输入。可以参考agentfabric项目中的[这里53-64行](https://github.com/modelscope/modelscope-agent/blob/master/apps/agentfabric/user_core.py#L53)的代码，这里是创建了一个memory，用于记录。
同时在[这里573-606行](https://github.com/modelscope/modelscope-agent/blob/master/apps/agentfabric/app.py#L573) 进行记录。
这两个地方一个是初始化memory，一个是利用memory的history做多轮。

我们会尽快再补一个简单的demo给到你。

**Comment by douyh** [comment]
> 通过history传递上一轮的输出，作为输入。可以参考agentfabric项目中的[这里53-64行](https://github.com/modelscope/modelscope-agent/blob/master/apps/agentfabric/user_core.py#L53)的代码，这里是创建了一个memory。 同时在[这里573-606行](https://github.com/modelscope/modelscope-agent/blob/master/apps/agentfabric/app.py#L573) 利用memory的history。 这两个地方一个是初始化memory，一个是利用memory的history做多轮。
> 
> 我们会尽快再补一个简单的demo给到你。

 我现在是简单地把role_play中的message yield出来，然后再次传入到下一轮中，比较粗暴，但是有效。
![image](https://github.com/modelscope/modelscope-agent/assets/34704737/67207e2c-59e3-4c2e-a2d6-7ffa38c87ee1)



![image](https://github.com/modelscope/modelscope-agent/assets/34704737/59732d38-9c94-4eca-ac77-cbe011b0552e)

**Comment by douyh** [comment]
> 通过history传递上一轮的输出，作为输入。可以参考agentfabric项目中的[这里53-64行](https://github.com/modelscope/modelscope-agent/blob/master/apps/agentfabric/user_core.py#L53)的代码，这里是创建了一个memory。 同时在[这里573-606行](https://github.com/modelscope/modelscope-agent/blob/master/apps/agentfabric/app.py#L573) 利用memory的history。 这两个地方一个是初始化memory，一个是利用memory的history做多轮。
> 
> 我们会尽快再补一个简单的demo给到你。

这个我学习一下

**Comment by XduSyL** [comment]
> > > 通过history传递上一轮的输出，作为输入。可以参考agentfabric项目中的[这里53-64行](https://github.com/modelscope/modelscope-agent/blob/master/apps/agentfabric/user_core.py#L53)的代码，这里是创建了一个memory。 同时在[这里573-606行](https://github.com/modelscope/modelscope-agent/blob/master/apps/agentfabric/app.py#L573) 利用memory的history。 这两个地方一个是初始化memory，一个是利用memory的history做多轮。
> > > 我们会尽快再补一个简单的demo给到你。
> > 
> > 
> > 这个我学习一下
> 
> 可以这么来，我们尽快也完善示例，如果你们有需求尽管通过pr提出来，会尽力支持。

可以的，非常感谢

**Comment by zzhangpurdue** [comment]
已经加了demo可以先看，如果有问题，可以重新开issue，或者reopen本轮。

**Comment by GitEasonXu** [comment]
https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md
origin/feat/qwen_vllm分支已经不存在了，开源项目维护的也太差了..

**Comment by wenmengzhou** [comment]
> https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md origin/feat/qwen_vllm分支已经不存在了，开源项目维护的也太差了..

https://github.com/modelscope/modelscope-agent/pull/374  has fixed this
