### ISSUE TITLE
[framework] AgentFabric应用中，user_agent的config更新异常

### ISSUE THREAD

**Issue by xyliugo** [modelscope/modelscope-agent#356]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have read and followed [the docs & demos](https://github.com/modelscope/modelscope-agent/tree/master/demo) and still think this is a bug
- [X] I am confident that the issue is with modelscope-agent (not my code, or another library in the ecosystem)

### What happened + What you expected to happen

在AgentFabric中，user_agent的config文件会出现更新异常，具体表现在，在builder_agent（左侧）中描述一个我想生成的agent后，user_agent（右侧）不会立即更新config文件，导致user_agent仍保持以前的config文件和状态。

![bug](https://github.com/modelscope/modelscope-agent/assets/118035138/63fce404-f302-4917-8356-b6bb744f75e3)

### Versions / Dependencies

Modelscope-agent: 0.3.0 (not sure)
Python: 3.10
OS: Mac

### Reproduction script

见上图

### Issue Severity

High: It blocks me from completing my task.

**Comment by mushenL** [comment]
您好，我这边试了一下，没有复现出来您说的问题，一般在修改了描述之后，需要点击更新配置才会生效，可以检查一下您是否点击了更新配置按钮，可以具体描述一下您这边可以复现的条件吗？
<img width="1359" alt="image" src="https://github.com/modelscope/modelscope-agent/assets/125954878/45f9c75e-c1b0-4954-ac03-ec0bb65b1ab2">
