### ISSUE TITLE
qwen_vllm分支什么时候会合入主分支呢？[<Agent component: framework|tool|llm|etc...>] 

### ISSUE THREAD

**Issue by douyh** [modelscope/modelscope-agent#364]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs & demos](https://github.com/modelscope/modelscope-agent/tree/master/demo) and still think this feature is missing

### Description

根据 https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md
描述，在本地部署的时候需要切换到`qwen_vllm`分支，请问这个分支什么时候会合入主分支呢？

**Comment by zzhangpurdue** [comment]
https://github.com/modelscope/modelscope-agent/pull/301/files

**Comment by wenmengzhou** [comment]
document has been updated in this pr https://github.com/modelscope/modelscope-agent/pull/374
