### ISSUE TITLE
请问如何调用远程的llm

### ISSUE THREAD

**Issue by zhuangdaAlx** [modelscope/modelscope-agent#39]
文档和代码里好像都是针对本地调用，请问怎么调用部署在远程的llm（比如部署在远程服务器上的qwen和modelscope-agent）呢？

**Comment by lcl6679292** [comment]
调用远程的llm现在支持两个，一个是chatgpt通过api-key既可以调用，另一个是ModelScopeGPT dashscope api版本。后者因为目前系统原因，暂停止了API申请，等后面恢复后会第一时间告知

**Comment by zhuangdaAlx** [comment]
你好！我已收到你的邮件，将在查看后回复。
