### ISSUE TITLE
和qwen-agent有啥区别？

### ISSUE THREAD

**Issue by njhouse365** [modelscope/modelscope-agent#458]
### Initial Checks

- [ ] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [ ] I have read and followed [the docs & demos](https://github.com/modelscope/modelscope-agent/tree/master/demo) and still think this is a bug
- [ ] I am confident that the issue is with modelscope-agent (not my code, or another library in the ecosystem)

### What happened + What you expected to happen

和qwen-agent有啥区别？

### Versions / Dependencies

和qwen-agent有啥区别？

### Reproduction script

和qwen-agent有啥区别？

### Issue Severity

None

**Comment by zzhangpurdue** [comment]
qwen-agent团队和我们共同维护了roleplay的能力，除此之外各自有一些侧重点。我们关注更广泛的tool生态，支持multi-agent，在多模态能力上也在做探索。

**Comment by jsxyhelu** [comment]
deepresearch肯定是modelscope这边的特点，也是值得应用的点。
