### ISSUE TITLE
[RAG] What is the best way to add RAG in Agent?

### ISSUE THREAD

**Issue by douyh** [modelscope/modelscope-agent#465]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs & demos](https://github.com/modelscope/modelscope-agent/tree/master/demo) and still think this feature is missing

### Description

I can see some examples of rag in `examples`.

![image](https://github.com/modelscope/modelscope-agent/assets/34704737/2009f8a3-0c4d-4e94-bee7-f21f187286b0)

I have a question. I don't want to call rag every time, that is, I don't want to add ref_doc directly beacuase of huge time comsumption. How can I decide what is the right time to use rag? Use rag as a tool? 

I hope to get some suggestions. Thanks.

**Comment by zzhangpurdue** [comment]
The best practice is to index file once, and save indexing file, there is no way to avoid the indexing step which cost `huge time`.

**Comment by suluyana** [comment]
Using rag as a tool may be a good idea, but the effect may be questionable. Or call llm first to decide whether the current round of query uses rag.

**Comment by douyh** [comment]
> The best practice is to index file once, and save indexing file, there is no way to avoid the indexing step which cost `huge time`, we default set the 'use_knowledge_cache' to True, to allow use cached indexing. BTW, we are upgrading our `RAG` ability, by using llama-index, user could easily apply the llama-index component in our agents.

I see. I will try llama-index. Thanks for your reply.
