### ISSUE TITLE
修改模型文件默认下载地址

### ISSUE THREAD

**Issue by Jeffrey9130** [modelscope/modelscope-agent#49]
尝试运行demo_qwen_agent.ipynb会触发模型文件的下载，默认下载地址是/home下的.cache文件夹，请问能修改这个默认下载地址到任意路径吗？

**Comment by yingdachen** [comment]
https://www.modelscope.cn/docs/%E6%A8%A1%E5%9E%8B%E7%9A%84%E4%B8%8B%E8%BD%BD

"默认模型会下载到~/.cache/modelscope/hub中，如果需要修改下载目录，可以手动指定环境变量：MODELSCOPE_CACHE，modelscope会将模型和数据集下载到该环境变量指定的目录中。"
