### ISSUE TITLE
demo_modelscopegpt_agent.ipynb 报错

### ISSUE THREAD

**Issue by Jeffrey9130** [modelscope/modelscope-agent#50]
运行agent.run时提示如下报错：
Code: 403, status: AccessDenied, message: Access denied.

已经提供两个key

**Comment by wenmengzhou** [comment]
您好，目前api已开放，参考readme在灵积平台（dashscope.aliyun.com）申请Qwen-7b模型权限后即可免费使用一定次数

**Comment by wenmengzhou** [comment]
> 没有在灵积上看到说要开通，qwen开源显示是直接可用的。本地已经用API key成功调用7b和14b的开源模型，但是这个notebook跑不通。
> 
> 今天的报错信息又变了：Code: 429, status: Throttling.AllocationQuota, message: Free allocated quota exceeded.
> 
> > 您好，目前api已开放，参考readme在灵积平台（dashscope.aliyun.com）开通服务后即可免费使用一定次数

您好，请反馈下您的阿里云uid

**Comment by Jeffrey9130** [comment]
1848788125517614

**Comment by Jeffrey9130** [comment]
> > 没有在灵积上看到说要开通，qwen开源显示是直接可用的。本地已经用API key成功调用7b和14b的开源模型，但是这个notebook跑不通。
> > 今天的报错信息又变了：Code: 429, status: Throttling.AllocationQuota, message: Free allocated quota exceeded.
> > > 您好，目前api已开放，参考readme在灵积平台（dashscope.aliyun.com）开通服务后即可免费使用一定次数
> 
> 您好，请反馈下您的阿里云uid

1848788125517614

**Comment by Jeffrey9130** [comment]
发现问题了，config里的模型名称没有对齐：

```json
"modelscope-agent": {
        "type": "dashscope",
        "model": "modelscope-agent-llm-v1" %这里应该是"qwen-14b/7b-chat" 才可以call到dashscope上的14b/7b的modal
        "generate_cfg": {
            "parameters":{
                "use_raw_prompt": true,
                "top_p": 0.8,
                "top_k": 10,
                "seed": 123,
                "debug": false
            }
        }
    },
```
建议更新一下文档啊

**Comment by zzclynn** [comment]
感谢提供建议，我们持续优化文档。
