### ISSUE TITLE
这个项目可以使用Qwen-14B作为核心模型吗？

### ISSUE THREAD

**Issue by zhuangdaAlx** [modelscope/modelscope-agent#53]
如果可以的话，要怎么修改配置？

**Comment by wenmengzhou** [comment]
> 我调用api接口，但是效果不行，目前agent版本api没开放

您好，目前api已开放，参考readme在灵积平台（dashscope.aliyun.com）申请Qwen-7b模型权限后即可免费使用一定次数

**Comment by xs818818** [comment]
> > 我调用api接口，但是效果不行，目前agent版本api没开放
> 
> 您好，目前api已开放，参考readme在灵积平台（dashscope.aliyun.com）申请Qwen-7b模型权限后即可免费使用一定次数

哪个api可以代替qwen-turbo，qwen-plus ，qwen-14b-chat，qwen-7b-chat.选哪个代替modelscope-agent-llm-v1

**Comment by wenmengzhou** [comment]
> > > 我调用api接口，但是效果不行，目前agent版本api没开放
> > 
> > 
> > 您好，目前api已开放，参考readme在灵积平台（dashscope.aliyun.com）申请Qwen-7b模型权限后即可免费使用一定次数
> 
> 哪个api可以代替qwen-turbo，qwen-plus ，qwen-14b-chat，qwen-7b-chat.选哪个代替modelscope-agent-llm-v1

申请qwen-7b后获取访问modelscope-agent-llm-v1的权限，model还是使用modelscope-agent-llm-v1，配置文件中填写sk即可

**Comment by wenmengzhou** [comment]
您好，经过调整， 目前只要开通dashscope服务，就可以访问modelscope-agent-llm-v1

**Comment by lcl6679292** [comment]
> 如果可以的话，要怎么修改配置？
Qwen-14B也是可以直接用的，我们后面也会推出一个modelscope-agent qwen-14b版本，欢迎后面来使用。如果现在直接用Qwen-14B的话config可以按照下面修改就可以

model_name = 'qwen-14b'
model_cfg = {
    'qwen-14b':{
        'type': 'modelscope',
        'model_id': 'qwen/Qwen-14B-Chat',
        'model_revision': 'v1.0.1',
        'use_raw_generation_config': True,
        'custom_chat': True
    }
}

**Comment by wengyuan722** [comment]
qwen-14b的response 要规定一下输出格式，不然很难用，另外想咨询一下多任务，这个是怎么拆解的

**Comment by zhuangdaAlx** [comment]
你好！我已收到你的邮件，将在查看后回复。

**Comment by zzclynn** [comment]
qwen-max目前是主要使用的模型，指令理解效果，以及角色扮演能力都很出色。

**Comment by zhuangdaAlx** [comment]
你好！我已收到你的邮件，将在查看后回复。
