### ISSUE TITLE
训练Agent模型的数据格式是怎么样的？

### ISSUE THREAD

**Issue by Mike4Ellis** [modelscope/modelscope-agent#55]
我尝试在Swift框架的基础上微调一个Agent模型，阅读源码之后我理解模型的输入为完整的文本内容包括（system、user、assistant），而label为所有assistant内容，这是为什么呢？

输入里为什么依旧存在assistant的内容？如果我去掉这一部分会有什么影响吗？希望能够得到解答！谢谢！

还有就是，Agent模型的微调可以直接用其他框架的SFT脚本吗（比如DeepSpeed）？还是说在优化任务上是有区别的？

**Comment by Zhikaiiii** [comment]
> 我尝试在Swift框架的基础上微调一个Agent模型，阅读源码之后我理解模型的输入为完整的文本内容包括（system、user、assistant），而label为所有assistant内容，这是为什么呢？
> 
> 输入里为什么依旧存在assistant的内容？如果我去掉这一部分会有什么影响吗？希望能够得到解答！谢谢！
> 
> 还有就是，Agent模型的微调可以直接用其他框架的SFT脚本吗（比如DeepSpeed）？还是说在优化任务上是有区别的？

这个输入的assistant和label的assistant事实上是错了一位的，即用[0...t]的token去预测t+1的token，所以输入还是保留了assistant。loss计算的时候也只计算assistant的部分。

问题2，我们的微调脚本就是基于Swift框架的，Swift框架也是支持DeepSpeed的，可能需要自己手动改配置

**Comment by Mike4Ellis** [comment]
> > 我尝试在Swift框架的基础上微调一个Agent模型，阅读源码之后我理解模型的输入为完整的文本内容包括（system、user、assistant），而label为所有assistant内容，这是为什么呢？
> > 输入里为什么依旧存在assistant的内容？如果我去掉这一部分会有什么影响吗？希望能够得到解答！谢谢！
> > 还有就是，Agent模型的微调可以直接用其他框架的SFT脚本吗（比如DeepSpeed）？还是说在优化任务上是有区别的？
> 
> 这个输入的assistant和label的assistant事实上是错了一位的，即用[0...t]的token去预测t+1的token，所以输入还是保留了assistant。loss计算的时候也只计算assistant的部分。
> 
> 问题2，我们的微调脚本就是基于Swift框架的，Swift框架也是支持DeepSpeed的，可能需要自己手动改配置

假如一次多轮对话为<system, user, assistant, user, assistant>，我理解经tokenize_function处理后为Inputs: <system, user, assistant, user, assistant>，而label: <[ignore], [ignore], assistant(llm_res, exec_res_ignore), [ignore], assistant(llm_res, exec_res_ignore)>，不是很理解这个错了一位是什么意思，并且为什么label中的exec_res也会被无视呢？

问这个主要是，我想知道基于其他框架的脚本进行训练时，数据处理或训练损失会不会有什么不同。

**Comment by Zhikaiiii** [comment]
> > > 我尝试在Swift框架的基础上微调一个Agent模型，阅读源码之后我理解模型的输入为完整的文本内容包括（system、user、assistant），而label为所有assistant内容，这是为什么呢？
> > > 输入里为什么依旧存在assistant的内容？如果我去掉这一部分会有什么影响吗？希望能够得到解答！谢谢！
> > > 还有就是，Agent模型的微调可以直接用其他框架的SFT脚本吗（比如DeepSpeed）？还是说在优化任务上是有区别的？
> > 
> > 
> > 这个输入的assistant和label的assistant事实上是错了一位的，即用[0...t]的token去预测t+1的token，所以输入还是保留了assistant。loss计算的时候也只计算assistant的部分。
> > 问题2，我们的微调脚本就是基于Swift框架的，Swift框架也是支持DeepSpeed的，可能需要自己手动改配置
> 
> 假如一次多轮对话为<system, user, assistant, user, assistant>，我理解经tokenize_function处理后为Inputs: <system, user, assistant, user, assistant>，而label: <[ignore], [ignore], assistant(llm_res, exec_res_ignore), [ignore], assistant(llm_res, exec_res_ignore)>，不是很理解这个错了一位是什么意思，并且为什么label中的exec_res也会被无视呢？
> 
> 问这个主要是，我想知道基于其他框架的脚本进行训练时，数据处理或训练损失会不会有什么不同。

错了一位的意思就是文本生成任务中，基于inputs会预测下一时刻的token，和label计算损失函数。其次，exec_res被无视是因为我认为LLM不需要去预测exec_res，而是应该基于exec_res做summary。
第二个问题，数据处理没有不一样。训练损失可能由于分布式相关的，好像无法完全对齐，但是应该差距不大。

**Comment by Mike4Ellis** [comment]
> > > > 我尝试在Swift框架的基础上微调一个Agent模型，阅读源码之后我理解模型的输入为完整的文本内容包括（system、user、assistant），而label为所有assistant内容，这是为什么呢？
> > > > 输入里为什么依旧存在assistant的内容？如果我去掉这一部分会有什么影响吗？希望能够得到解答！谢谢！
> > > > 还有就是，Agent模型的微调可以直接用其他框架的SFT脚本吗（比如DeepSpeed）？还是说在优化任务上是有区别的？
> > > 
> > > 
> > > 这个输入的assistant和label的assistant事实上是错了一位的，即用[0...t]的token去预测t+1的token，所以输入还是保留了assistant。loss计算的时候也只计算assistant的部分。
> > > 问题2，我们的微调脚本就是基于Swift框架的，Swift框架也是支持DeepSpeed的，可能需要自己手动改配置
> > 
> > 
> > 假如一次多轮对话为<system, user, assistant, user, assistant>，我理解经tokenize_function处理后为Inputs: <system, user, assistant, user, assistant>，而label: <[ignore], [ignore], assistant(llm_res, exec_res_ignore), [ignore], assistant(llm_res, exec_res_ignore)>，不是很理解这个错了一位是什么意思，并且为什么label中的exec_res也会被无视呢？
> > 问这个主要是，我想知道基于其他框架的脚本进行训练时，数据处理或训练损失会不会有什么不同。
> 
> 错了一位的意思就是文本生成任务中，基于inputs会预测下一时刻的token，和label计算损失函数。其次，exec_res被无视是因为我认为LLM不需要去预测exec_res，而是应该基于exec_res做summary。 第二个问题，数据处理没有不一样。训练损失可能由于分布式相关的，好像无法完全对齐，但是应该差距不大。

这个时间的粒度是怎么样的呀？我理解是对于样本<system, user, assistant, user, assistant>，会先基于<system, user>预测t时刻的assistant，再基于<system, user, assistant, user>预测t+1时刻的assistant？
然后计算损失时会比较label中assistant与预测assistant中llm_res的结果。

请问我的理解对吗？

**Comment by Mike4Ellis** [comment]
> > > > > 我尝试在Swift框架的基础上微调一个Agent模型，阅读源码之后我理解模型的输入为完整的文本内容包括（system、user、assistant），而label为所有assistant内容，这是为什么呢？
> > > > > 输入里为什么依旧存在assistant的内容？如果我去掉这一部分会有什么影响吗？希望能够得到解答！谢谢！
> > > > > 还有就是，Agent模型的微调可以直接用其他框架的SFT脚本吗（比如DeepSpeed）？还是说在优化任务上是有区别的？
> > > > 
> > > > 
> > > > 这个输入的assistant和label的assistant事实上是错了一位的，即用[0...t]的token去预测t+1的token，所以输入还是保留了assistant。loss计算的时候也只计算assistant的部分。
> > > > 问题2，我们的微调脚本就是基于Swift框架的，Swift框架也是支持DeepSpeed的，可能需要自己手动改配置
> > > 
> > > 
> > > 假如一次多轮对话为<system, user, assistant, user, assistant>，我理解经tokenize_function处理后为Inputs: <system, user, assistant, user, assistant>，而label: <[ignore], [ignore], assistant(llm_res, exec_res_ignore), [ignore], assistant(llm_res, exec_res_ignore)>，不是很理解这个错了一位是什么意思，并且为什么label中的exec_res也会被无视呢？
> > > 问这个主要是，我想知道基于其他框架的脚本进行训练时，数据处理或训练损失会不会有什么不同。
> > 
> > 
> > 错了一位的意思就是文本生成任务中，基于inputs会预测下一时刻的token，和label计算损失函数。其次，exec_res被无视是因为我认为LLM不需要去预测exec_res，而是应该基于exec_res做summary。 第二个问题，数据处理没有不一样。训练损失可能由于分布式相关的，好像无法完全对齐，但是应该差距不大。
> 
> 这个时间的粒度是怎么样的呀？我理解是对于样本<system, user, assistant, user, assistant>，会先基于<system, user>预测t时刻的assistant，再基于<system, user, assistant, user>预测t+1时刻的assistant？ 然后计算损失时会比较label中assistant与预测assistant中llm_res的结果。
> 
> 请问我的理解对吗？

顶一下，不知道有人能解答吗？

**Comment by Zhikaiiii** [comment]
> > > > > 我尝试在Swift框架的基础上微调一个Agent模型，阅读源码之后我理解模型的输入为完整的文本内容包括（system、user、assistant），而label为所有assistant内容，这是为什么呢？
> > > > > 输入里为什么依旧存在assistant的内容？如果我去掉这一部分会有什么影响吗？希望能够得到解答！谢谢！
> > > > > 还有就是，Agent模型的微调可以直接用其他框架的SFT脚本吗（比如DeepSpeed）？还是说在优化任务上是有区别的？
> > > > 
> > > > 
> > > > 这个输入的assistant和label的assistant事实上是错了一位的，即用[0...t]的token去预测t+1的token，所以输入还是保留了assistant。loss计算的时候也只计算assistant的部分。
> > > > 问题2，我们的微调脚本就是基于Swift框架的，Swift框架也是支持DeepSpeed的，可能需要自己手动改配置
> > > 
> > > 
> > > 假如一次多轮对话为<system, user, assistant, user, assistant>，我理解经tokenize_function处理后为Inputs: <system, user, assistant, user, assistant>，而label: <[ignore], [ignore], assistant(llm_res, exec_res_ignore), [ignore], assistant(llm_res, exec_res_ignore)>，不是很理解这个错了一位是什么意思，并且为什么label中的exec_res也会被无视呢？
> > > 问这个主要是，我想知道基于其他框架的脚本进行训练时，数据处理或训练损失会不会有什么不同。
> > 
> > 
> > 错了一位的意思就是文本生成任务中，基于inputs会预测下一时刻的token，和label计算损失函数。其次，exec_res被无视是因为我认为LLM不需要去预测exec_res，而是应该基于exec_res做summary。 第二个问题，数据处理没有不一样。训练损失可能由于分布式相关的，好像无法完全对齐，但是应该差距不大。
> 
> 这个时间的粒度是怎么样的呀？我理解是对于样本<system, user, assistant, user, assistant>，会先基于<system, user>预测t时刻的assistant，再基于<system, user, assistant, user>预测t+1时刻的assistant？ 然后计算损失时会比较label中assistant与预测assistant中llm_res的结果。
> 
> 请问我的理解对吗？

嗯嗯可以这么理解

**Comment by Mike4Ellis** [comment]
> > > > > > 我尝试在Swift框架的基础上微调一个Agent模型，阅读源码之后我理解模型的输入为完整的文本内容包括（system、user、assistant），而label为所有assistant内容，这是为什么呢？
> > > > > > 输入里为什么依旧存在assistant的内容？如果我去掉这一部分会有什么影响吗？希望能够得到解答！谢谢！
> > > > > > 还有就是，Agent模型的微调可以直接用其他框架的SFT脚本吗（比如DeepSpeed）？还是说在优化任务上是有区别的？
> > > > > 
> > > > > 
> > > > > 这个输入的assistant和label的assistant事实上是错了一位的，即用[0...t]的token去预测t+1的token，所以输入还是保留了assistant。loss计算的时候也只计算assistant的部分。
> > > > > 问题2，我们的微调脚本就是基于Swift框架的，Swift框架也是支持DeepSpeed的，可能需要自己手动改配置
> > > > 
> > > > 
> > > > 假如一次多轮对话为<system, user, assistant, user, assistant>，我理解经tokenize_function处理后为Inputs: <system, user, assistant, user, assistant>，而label: <[ignore], [ignore], assistant(llm_res, exec_res_ignore), [ignore], assistant(llm_res, exec_res_ignore)>，不是很理解这个错了一位是什么意思，并且为什么label中的exec_res也会被无视呢？
> > > > 问这个主要是，我想知道基于其他框架的脚本进行训练时，数据处理或训练损失会不会有什么不同。
> > > 
> > > 
> > > 错了一位的意思就是文本生成任务中，基于inputs会预测下一时刻的token，和label计算损失函数。其次，exec_res被无视是因为我认为LLM不需要去预测exec_res，而是应该基于exec_res做summary。 第二个问题，数据处理没有不一样。训练损失可能由于分布式相关的，好像无法完全对齐，但是应该差距不大。
> > 
> > 
> > 这个时间的粒度是怎么样的呀？我理解是对于样本<system, user, assistant, user, assistant>，会先基于<system, user>预测t时刻的assistant，再基于<system, user, assistant, user>预测t+1时刻的assistant？ 然后计算损失时会比较label中assistant与预测assistant中llm_res的结果。
> > 请问我的理解对吗？
> 
> 我刚刚说的时间粒度是每一个token。但是整体流程确实如你所说，基于<system, user>预测下一轮的assistant，再基于<system, user, assistant, user>预测新一轮的assistant？ 然后计算损失时会比较label中assistant与预测assistant中llm_res的结果。

好的，我明白了，十分感谢解答！
