### ISSUE TITLE
基于Qwen-7B-Base模型微调后，推理生成均为乱码

### ISSUE THREAD

**Issue by Mike4Ellis** [modelscope/modelscope-agent#57]
我利用该框架基于Qwen-7B模型进行了SFT微调，之后以Agent的形式进行加载、推理，之后发现模型输出的均为乱码。

我观察到Qwen的base版与Agent版的modeling.py等代码以及config.json均有较大差异，我也尝试更换为base版的config但是会报错`AttributeError: 'QWenConfig' object has no attribute 'padded_vocab_size'`，请问如果我要自己基于Qwen训练一个agent模型该如何正确使用呢？

![image](https://github.com/modelscope/modelscope-agent/assets/35845420/fb87b72d-c676-428f-b875-6b76faa4354c)

**Comment by yyy4444** [comment]
我遇到同样的问题了，兄弟，你解决了吗？
