### ISSUE TITLE
本地大模型、向量模型的支持

### ISSUE THREAD

**Issue by RyanOvO** [modelscope/modelscope-agent#577]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs & demos](https://github.com/modelscope/modelscope-agent/tree/master/demo) and still think this feature is missing

### Description

能理解官方希望相关的基础设施是对接线上的魔塔；但很多时候受限于环境和要求，只能用本地部署运行的模型（AI，向量等），甚至服务器环境都是没有网络只能手动传模型文件部署开发。

希望官方能支持OpenAI规范对接的向量，模型等接口接入。

**Comment by jsxyhelu** [comment]
export OPENAI_API_KEY=API_key
export OPENAI_BASE_URL=https://127.0.0.1/v1/
export OPENAI_MODEL_ID=Qwen/Qwen3-235B-A22B-Instruct-2507
输入进行后尝试一下了？我是在离线部署的时候遇到以下问题：https://github.com/modelscope/ms-agent/discussions/723
