### ISSUE TITLE
自定义tools的时候，如果参数是多层字典怎么办

### ISSUE THREAD

**Issue by gonkillu** [modelscope/modelscope-agent#58]
问题：自定义tools的时候，如果参数是多层字典怎么办

自定义tools时，params的格式是参数信息的列表，那如果我的参数需要这样的：
`{
   'name':'',
   'id':{'id':'1',   'position':'a'}
}`
请问这样的参数应该如何添加？

**Comment by wenmengzhou** [comment]
tools参数定义时尽量保持一级参数，可以在内部组合成多级的结构进行其他接口调用

**Comment by zzhangpurdue** [comment]
长时间未响应，有问题重新开。
