### ISSUE TITLE
能否使用本地的CHATGLM2模型？

### ISSUE THREAD

**Issue by SKY-ZW** [modelscope/modelscope-agent#60]
能否使用本地的CHATGLM2模型，需要修改哪里的配置呢，有具体修改实例教程吗

**Comment by zheng157** [comment]
同问

**Comment by soujie** [comment]
我试了下, 可以用本地原生的chatglm2 6b 的模型进行推理, 但是效果没法看, 应该需要结合给的工具调用数据集微调下模型.

**Comment by gao-stu** [comment]
> 我试了下, 可以用本地原生的chatglm2 6b 的模型进行推理, 但是效果没法看, 应该需要结合给的工具调用数据集微调下模型.

请问怎么配置呢

**Comment by qxhuang123** [comment]
> 我试了下, 可以用本地原生的chatglm2 6b 的模型进行推理, 但是效果没法看, 应该需要结合给的工具调用数据集微调下模型.

请问怎么配置呢？

**Comment by soujie** [comment]
我是本地起一个glm2 的openai api , 继承LLM新起一个类, 用requests.post 实现一下generate 功能就行了

**Comment by XduSyL** [comment]
请问如果我不用api的方式，而是用agent去调用本地的LLM，比如说qwen-7b,需要怎么操作啊，也不需要用gradio，就用RolePlay来调用，请问下是不是要继承BaseChatModel这个类，重写一个本地的LLM类，能不能麻烦提供一下demo，我看挺多人都有这个问题的

**Comment by zzhangpurdue** [comment]
可以，也可以使用本地拉起vllm的方式，参考
https://github.com/modelscope/modelscope-agent/blob/master/demo/demo_qwen_local_llm.ipynb

**Comment by zzhangpurdue** [comment]
No response over 1 month, close this issue, reopen it if any follow questions.
