### ISSUE TITLE
这些报错是怎么解决呀

### ISSUE THREAD

**Issue by zheng157** [modelscope/modelscope-agent#61]
![image](https://github.com/modelscope/modelscope-agent/assets/141010882/3b58e5f1-b398-4eb8-b986-0673a6e0bddd)

**Comment by Zhikaiiii** [comment]
> ![image](https://user-images.githubusercontent.com/141010882/274789660-3b58e5f1-b398-4eb8-b986-0673a6e0bddd.png)

这是modelscope导入模型的warning，不影响正常使用，可以忽略。

**Comment by zheng157** [comment]
好的  谢谢
