### ISSUE TITLE
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by SKY-ZW** [modelscope/modelscope-agent#64]
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'    聊天时候报错

**Comment by Zhikaiiii** [comment]
> RuntimeError: "addmm_impl_cpu_" not implemented for 'Half' 聊天时候报错

请问你使用的模型，以及对应的modelscope版本是什么呢？可以尝试使用最新版的modelscope并查看相关模型的使用示例。

**Comment by xinwenhh** [comment]
> RuntimeError: "addmm_impl_cpu_" not implemented for 'Half' 聊天时候报错

这个是gpu内存不够的问题，我也遇到过，你可以杀掉一些运行的进程

**Comment by zzhangpurdue** [comment]
感谢反馈，目前看可以通过api调用qwen-max效果能非常稳定

**Comment by zzhangpurdue** [comment]
长时间未响应，有问题重新开。
