### ISSUE TITLE
如何配置 offload_folder 参数？

### ISSUE THREAD

**Issue by zlei1989** [modelscope/modelscope-agent#65]
运行 `demo_qwen_agent.ipynb` 报下面这个错误，请问配置 `offload_folder` 能解决吗？怎么配置？

```
The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.
```

**Comment by Zhikaiiii** [comment]
> 运行 `demo_qwen_agent.ipynb` 报下面这个错误，请问配置 `offload_folder` 能解决吗？怎么配置？
> 
> ```
> The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.
> ```

我在自己的环境下运行没有抱这个错误。能麻烦提供一下您的运行环境和modelscope版本吗？

**Comment by wang1061709572** [comment]
> > 运行 `demo_qwen_agent.ipynb` 报下面这个错误，请问配置 `offload_folder` 能解决吗？怎么配置？
> > ```
> > The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.
> > ```
> 
> 我在自己的环境下运行没有抱这个错误。能麻烦提供一下您的运行环境和modelscope版本吗？

你好，我也遇到了这个问题

**Comment by wang1061709572** [comment]
环境

**Comment by wang1061709572** [comment]
python:3.10.8

**Comment by wang1061709572** [comment]
1. python：3.10.8
2. mac：macOS Monterey 12.6
3. cpu：2.3 GHz 四核Intel Core i5
4. modelscope版本：1.9.5

**Comment by wenmengzhou** [comment]
@wang1061709572 这是显存不够大，触发了transformers的offload能力，请尝试使用api进行llm访问

**Comment by alittlebitfun** [comment]
是不是装了cpu版本的torch

**Comment by zzhangpurdue** [comment]
长时间未响应，有问题重新开。
