### ISSUE TITLE
项目目前是没有适配chatglm3吗

### ISSUE THREAD

**Issue by hihanyi** [modelscope/modelscope-agent#68]
利用swift微调出来的glm3-6b在这个项目上的表现很差, 基本没有效果, 但是微调时的infer效果看着还行

**Comment by wenmengzhou** [comment]
您好，chatglm3-6b的agent能力目前还没有接入，对应的prompt格式需要做适配，后续会支持

**Comment by zzhangpurdue** [comment]
zhipu chatglm4已经接入，请查看最新的代码。
