### ISSUE TITLE
调用同一个工具重复多次

### ISSUE THREAD

**Issue by bwin90** [modelscope/modelscope-agent#69]
![image](https://github.com/modelscope/modelscope-agent/assets/9714028/fef5c472-2baa-4e01-b910-dd15d4ddf684)

response = agent.run("从下面的地址中找到省市区等元素，地址：上海市静安区大宁音乐广场三期A3栋403室", print_info=True)

最后的输出如下：

[{'result': {'city': '上海市', 'district': '静安区', 'poi': '大宁音乐广场', 'subpoi': '三期', 'houseno': 'A3栋'}}, {'result': {'city': '上海市', 'district': '静安区', 'poi': '大宁音乐广场', 'subpoi': '三期', 'houseno': 'A3栋'}}, {'result': {'city': '上海市', 'district': '静安区', 'poi': '大宁音乐广场', 'subpoi': '三期', 'houseno': 'A3栋'}}, {'result': {'city': '上海市', 'district': '静安区', 'poi': '大宁音乐广场', 'subpoi': '三期', 'houseno': 'A3栋'}}, {'result': {'city': '上海市', 'district': '静安区', 'poi': '大宁音乐广场', 'subpoi': '三期', 'houseno': 'A3栋'}}, {'result': {'city': '上海市', 'district': '静安区', 'poi': '大宁音乐广场', 'subpoi': '三期', 'houseno': 'A3栋'}}, {'result': {'city': '上海市', 'district': '静安区', 'poi': '大宁音乐广场', 'subpoi': '三期', 'houseno': 'A3栋'}}, {'result': {'city': '上海市', 'district': '静安区', 'poi': '大宁音乐广场', 'subpoi': '三期', 'houseno': 'A3栋'}}, {'result': {'city': '上海市', 'district': '静安区', 'poi': '大宁音乐广场', 'subpoi': '三期', 'houseno': 'A3栋'}}, {'result': {'city': '上海市', 'district': '静安区', 'poi': '大宁音乐广场', 'subpoi': '三期', 'houseno': 'A3栋'}}, {'result': {'city': '上海市', 'district': '静安区', 'poi': '大宁音乐广场', 'subpoi': '三期', 'houseno': 'A3栋'}}, {'result': {'city': '上海市', 'district': '静安区', 'poi': '大宁音乐广场', 'subpoi': '三期', 'houseno': 'A3栋'}}, {'result': {'city': '上海市', 'district': '静安区', 'poi': '大宁音乐广场', 'subpoi': '三期', 'houseno': 'A3栋'}}]

模型没有正确结束，这种情况是模型训练的问题吗？

**Comment by zzclynn** [comment]
具体上面代码可以再发一下

**Comment by fanbooo** [comment]
同问

**Comment by kapiya** [comment]
同问

**Comment by kapiya** [comment]
同问

**Comment by kapiya** [comment]
我也遇到类似的问题，请问解决了吗

**Comment by zzhangpurdue** [comment]
还是模型能力待提升，目前采用qwen-max可以完成，如果还不行，可能需要调整一下prompt。

**Comment by zzhangpurdue** [comment]
长时间未响应，有问题重新开。
