### ISSUE TITLE
近期没有更新了吗

### ISSUE THREAD

**Issue by chenyuqiang234** [modelscope/modelscope-agent#71]
近期关于agent没有更新了吗

**Comment by wenmengzhou** [comment]
您好，近期我们制作的story-agent在PR中，可以参考 https://github.com/modelscope/modelscope-agent/pull/66
另外我们基于modelscope-agent接入了Facechain，为Facechain项目提供了agent接口使用，可以参考 https://github.com/modelscope/facechain/tree/feat/facechain_agent/demo/facechain_agent

还有一些近期框架能力完善的工作在内部进行中，我们后续会给出roadmap，也欢迎大家提出新的feature需求
