### ISSUE TITLE
调用dashscope模型时，模型无法按照json格式回答工具调用信息

### ISSUE THREAD

**Issue by 24032655** [modelscope/modelscope-agent#76]
[demo_register_new_tool.md](https://github.com/modelscope/modelscope-agent/files/13359340/demo_register_new_tool.md)
附件为.ipynb文件，请修改扩展名后查看。

问题描述：
本地没有GPU，所以采用dashscope调用模式，调试用的notebook请见附件。
模型没有返回json格式的工具信息，而是一段文本。导致后续无法实现工具调用。

**Comment by zzclynn** [comment]
看起来这个模型没有follow 指令，你用的是哪个模型？

**Comment by 24032655** [comment]
https://github.com/modelscope/modelscope-agent/blob/.../config/cfg_model_template.json中的配置信息

    "modelscope-agent": {
        "type": "dashscope",
        "model": "modelscope-agent-llm-v1",
        "generate_cfg": {
            "parameters":{
                "use_raw_prompt": true,
                "top_p": 0.8,
                "top_k": 10,
                "seed": 123,
                "debug": false
            }
        }
    },

**Comment by zzhangpurdue** [comment]
可以尝试用qwen-max，目前指令理解效果最好

**Comment by 24032655** [comment]
谢谢。
