### ISSUE TITLE
安装dashscope失败

### ISSUE THREAD

**Issue by DoverDW** [modelscope/modelscope-agent#80]
ERROR: Could not find a version that satisfies the requirement dashscope (from versions: none)
ERROR: No matching distribution found for dashscope
安装requirements文件时，安装dashscope失败。如何解决

**Comment by wenmengzhou** [comment]
请在python3环境下使用，如果还不行，可以在pypi上下载whl安装  https://pypi.org/project/dashscope/#files

**Comment by y-zh** [comment]
![image](https://github.com/user-attachments/assets/5c626a0d-41ba-48e0-baf7-4007e5e3ec6b)

问题重现了，请问 对Python3的版本有要求吗？

**Comment by zzhangpurdue** [comment]
>=3.8
