### ISSUE TITLE
MODELSCOPE_API_TOKEN在哪里申请

### ISSUE THREAD

**Issue by xs818818** [modelscope/modelscope-agent#81]
调用插件进行图像生成。

{"api_name": "modelscope_image-generation", 
"parameters": {"text": "一只可爱的小狗"}}

很抱歉，我无法直接绘制出图像。但是，我可以帮助您生成一张与您的指令相关的图像描述。您可以尝试在搜索引擎上搜索这个描述以找到相应的图像。

**Comment by zzclynn** [comment]
https://modelscope.cn/my/myaccesstoken
这里可以看到

**Comment by xs818818** [comment]
是SDK令牌呀，奇怪了app.py需要有其它设置吗，我确实不能调用

**Comment by wenmengzhou** [comment]
具体是哪个app.py？ 有什么报错信息？

**Comment by zzhangpurdue** [comment]
长时间未响应，有问题重新开。
