### ISSUE TITLE
基于PAI-DSW-GPU环境执行命令报错

### ISSUE THREAD

**Issue by chuenfaiy** [modelscope/modelscope-agent#96]
测试demo：demo_qwen_agent.ipynb
用的实例自带的python版本：3.8
![image](https://github.com/modelscope/modelscope-agent/assets/10596044/e2f71765-5236-4adf-b939-b8f6de693dae)

**Comment by sandove** [comment]
遇到了同样的问题，估计是哪更新了没适配

**Comment by zzclynn** [comment]
已经更新，拉最新代码可以解决

**Comment by zzhangpurdue** [comment]
长时间未响应，有问题重新开。
