### ISSUE TITLE
CUDA报错，gpu报错

### ISSUE THREAD

**Issue by qxhuang123** [modelscope/modelscope-agent#99]
s/transformers_modules/ModelScope-Agent-7B/modeling.py", line 1208, in forward
    output = self._norm(x.float()).type_as(x)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by zzclynn** [comment]
你是在什么型号GPU上跑的？

**Comment by jinluyang** [comment]
GPU内存不够了

**Comment by zzhangpurdue** [comment]
gpu oom，后会不出现这个报错，确实gpu不够

**Comment by zzhangpurdue** [comment]
长时间未响应，有问题重新开。
